# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from fastapi import Request
from mindweaver.platform_service.ranger import RangerPlatform, RangerPlatformService
from mindweaver.fw.model import AsyncSession
from pydantic import ValidationError


@pytest.fixture
def mock_service_dependencies():
    request = MagicMock(spec=Request)
    session = MagicMock(spec=AsyncSession)
    session.exec = AsyncMock()
    session.flush = AsyncMock()
    return request, session


def test_ranger_resource_defaults():
    """Test default values for Ranger resource limits"""
    model = RangerPlatform(
        name="test-ranger", title="Test Ranger", project_id=1, database_id=10
    )
    assert model.cpu_request == 1.0
    assert model.cpu_limit == 2.0
    assert model.mem_request == 2.0
    assert model.mem_limit == 4.0
    assert model.solr_id is None


def test_ranger_validation():
    """Test validation logic for Ranger"""
    # Invalid CPU: request > limit
    with pytest.raises(ValidationError) as excinfo:
        RangerPlatform.model_validate(
            {
                "name": "test-ranger",
                "title": "Test Ranger",
                "project_id": 1,
                "database_id": 10,
                "cpu_request": 3.0,
                "cpu_limit": 2.0,
            }
        )
    assert "CPU request cannot be greater than CPU limit" in str(excinfo.value)


@pytest.mark.asyncio
async def test_ranger_template_vars(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        admin_password="admin",
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    # Mock PgSqlPlatformService
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ):
        vars = await svc.template_vars(model)

        assert vars["name"] == "test-ranger"
        assert vars["db_host"] == "test-db-pooler-rw.test-ns.svc.cluster.local"
        assert vars["db_user"] == "user"
        assert vars["db_pass"] == "pass"
        assert vars["admin_password"] == "admin"

        # Test with additional_properties
        model.additional_properties = {
            "ranger.test.prop": "value1",
            "another.prop": "value2",
        }
        vars = await svc.template_vars(model)
        assert vars["additional_properties"]["ranger.test.prop"] == "value1"
        assert vars["additional_properties"]["another.prop"] == "value2"
        assert vars["additional_properties"]["policymgr_http_enabled"] == "false"
        assert (
            vars["additional_properties"]["ranger.keystore.file"]
            == "/etc/ranger/tls/keystore.jks"
        )
        assert vars["additional_properties"]["ranger.keystore.password"] == "changeit"
        assert (
            vars["additional_properties"]["ranger.truststore.file"]
            == "/etc/ranger/truststore/truststore.jks"
        )
        assert vars["additional_properties"]["ranger.truststore.password"] == "changeit"


@pytest.mark.asyncio
async def test_ranger_password_generation(mock_service_dependencies):
    """Test that passwords are autogenerated during creation"""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
    )

    # Initial passwords should be None (after user removed defaults)
    assert model.admin_password is None

    # Trigger before_create hook
    await svc.generate_passwords(model)

    # Passwords should now be generated
    assert model.admin_password != "rangerR0cks!"
    assert len(model.admin_password) == 18
    assert model.keyadmin_password != "rangerR0cks!"
    assert len(model.keyadmin_password) == 18
    assert model.tagsync_password != "rangerR0cks!"
    assert len(model.tagsync_password) == 18
    assert model.usersync_password != "rangerR0cks!"
    assert len(model.usersync_password) == 18

    # Check complexity (at least one of each)
    import string

    def check_complexity(p):
        has_lower = any(c in string.ascii_lowercase for c in p)
        has_upper = any(c in string.ascii_uppercase for c in p)
        has_digit = any(c in string.digits for c in p)
        # Support both URI-safe and legacy symbols
        symbols = "!@#$%^&*()_+-=[]{}|;:,.<>?-_.~"
        has_symbol = any(c in symbols for c in p)
        return has_lower and has_upper and has_digit and has_symbol

    assert check_complexity(model.admin_password)
    assert check_complexity(model.keyadmin_password)
    assert check_complexity(model.tagsync_password)
    assert check_complexity(model.usersync_password)


@pytest.mark.asyncio
async def test_ranger_invalid_db(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    # Mock PgSql as inactive
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = False
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ):
        with pytest.raises(ValueError, match="is not active"):
            await svc.template_vars(model)


@pytest.mark.asyncio
async def test_ranger_render_manifests(mock_service_dependencies):
    """Test that Ranger manifests render correct additional properties for limiting service-defs"""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        admin_password="admin",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ):
        # Default behavior: policymgr_supportedcomponents should be rendered
        manifests = await svc.render_manifests(model)
        assert (
            "policymgr_supportedcomponents: trino,kafka,elasticsearch" in manifests
        )
        assert "ranger.supportedcomponents: trino,kafka,elasticsearch" in manifests
        assert "javaOpts:" in manifests
        # Default behavior: usersync should be disabled
        assert "enabled: false" in manifests
 
        # Custom override in additional_properties
        model.additional_properties = {
            "policymgr_supportedcomponents": "kafka,trino",
            "ranger.supportedcomponents": "kafka,trino",
            "custom.property": "value",
        }
        manifests_custom = await svc.render_manifests(model)
        assert "policymgr_supportedcomponents: kafka,trino" in manifests_custom
        assert "ranger.supportedcomponents: kafka,trino" in manifests_custom
        assert "custom.property: value" in manifests_custom
        # Ensure default list doesn't appear when overridden
        assert (
            "policymgr_supportedcomponents: trino,kafka,elasticsearch"
            not in manifests_custom
        )

        # Test with SYNC_SOURCE=ldap should enable usersync
        model.additional_properties = {
            "SYNC_SOURCE": "ldap",
        }
        manifests_ldap = await svc.render_manifests(model)
        assert "enabled: true" in manifests_ldap


@pytest.mark.asyncio
async def test_ranger_template_vars_with_solr(mock_service_dependencies):
    """Test that template_vars properly constructs Solr properties when solr_id is provided."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        solr_id=200,
        admin_password="admin",
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    # Mock PgSqlPlatformService
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # Mock SolrPlatformService
    mock_solr_svc = AsyncMock()
    mock_solr_model = MagicMock()
    mock_solr_model.name = "test-solr"
    mock_solr_svc.get.return_value = mock_solr_model
    mock_solr_svc._resolve_namespace = AsyncMock(return_value="solr-ns")

    mock_solr_state = MagicMock()
    mock_solr_state.active = True
    # admin_password is used by the init container to create the ranger_audits collection
    mock_solr_state.admin_password = "solr-admin-password"
    # solr_user_password is the password for the 'solr' user, used by Ranger audit writes
    mock_solr_state.solr_user_password = "solr-user-password"
    mock_solr_state.solr_internal_url = (
        "https://test-solr-solrcloud-common.solr-ns.svc.cluster.local:8983"
    )
    mock_solr_svc.platform_state.return_value = mock_solr_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.SolrPlatformService.get_service",
        AsyncMock(return_value=mock_solr_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.decrypt_password",
        side_effect=lambda x: x,
    ):

        vars = await svc.template_vars(model)

        assert vars["name"] == "test-ranger"
        assert vars["db_host"] == "test-db-pooler-rw.test-ns.svc.cluster.local"
        assert vars["additional_properties"]["audit_store"] == "solr"
        assert (
            vars["additional_properties"]["audit_solr_urls"]
            == "https://test-solr-solrcloud-common.solr-ns.svc.cluster.local:8983/solr/ranger_audits"
        )
        # Init container template vars
        assert (
            vars["solr_audit_url"]
            == "https://test-solr-solrcloud-common.solr-ns.svc.cluster.local:8983"
        )
        assert vars["solr_audit_admin_password"] == "solr-admin-password"
        assert vars["solr_audit_solr_password"] == "solr-user-password"


@pytest.mark.asyncio
async def test_ranger_invalid_solr(mock_service_dependencies):
    """Test that template_vars raises ValueError if the associated Solr instance is inactive."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        solr_id=200,
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    # Mock PgSql
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # Mock Solr as inactive
    mock_solr_svc = AsyncMock()
    mock_solr_model = MagicMock()
    mock_solr_model.name = "test-solr"
    mock_solr_svc.get.return_value = mock_solr_model
    mock_solr_state = MagicMock()
    mock_solr_state.active = False
    mock_solr_svc.platform_state.return_value = mock_solr_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.SolrPlatformService.get_service",
        AsyncMock(return_value=mock_solr_svc),
    ):
        with pytest.raises(ValueError, match="is not active"):
            await svc.template_vars(model)


@pytest.mark.asyncio
async def test_ranger_template_vars_with_ldap(mock_service_dependencies):
    """Test that template_vars properly constructs LDAP properties when project has ldap_config_id."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        admin_password="admin",
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project
    mock_project = MagicMock()
    mock_project.ldap_config_id = 500
    svc.project = AsyncMock(return_value=mock_project)

    # Mock PgSqlPlatformService
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # Mock LdapConfigService
    mock_ldap_svc = AsyncMock()
    mock_ldap_config = MagicMock()
    mock_ldap_config.server_url = "ldap://ldap.example.com:389"
    mock_ldap_config.bind_dn = "cn=admin,dc=example,dc=com"
    mock_ldap_config.bind_password = "ldap-secret-password"
    mock_ldap_config.user_search_base = "ou=users,dc=example,dc=com"
    mock_ldap_config.user_search_filter = "(uid={0})"
    mock_ldap_config.username_attr = "uid"
    mock_ldap_config.group_search_base = "ou=groups,dc=example,dc=com"
    mock_ldap_config.group_search_filter = "(member={0})"
    mock_ldap_config.group_member_attr = "member"
    mock_ldap_svc.get.return_value = mock_ldap_config

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.LdapConfigService.get_service",
        AsyncMock(return_value=mock_ldap_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.decrypt_password", lambda x: x
    ):

        vars = await svc.template_vars(model)

        assert vars["name"] == "test-ranger"
        additional_props = vars["additional_properties"]

        # Admin authentication properties
        assert additional_props["authentication_method"] == "LDAP"
        assert additional_props["xa_ldap_url"] == "ldap://ldap.example.com:389"
        assert additional_props["xa_ldap_bind_dn"] == "cn=admin,dc=example,dc=com"
        assert additional_props["xa_ldap_bind_password"] == "ldap-secret-password"
        assert additional_props["xa_ldap_base_dn"] == "ou=users,dc=example,dc=com"
        assert (
            additional_props["xa_ldap_userDNpattern"]
            == "uid={0},ou=users,dc=example,dc=com"
        )
        assert additional_props["xa_ldap_userSearchFilter"] == "(uid={0})"
        assert (
            additional_props["xa_ldap_groupSearchBase"] == "ou=groups,dc=example,dc=com"
        )
        assert additional_props["xa_ldap_groupSearchFilter"] == "(member={0})"
        assert additional_props["xa_ldap_groupRoleAttribute"] == "member"

        # UserSync properties
        assert additional_props["SYNC_SOURCE"] == "ldap"
        assert additional_props["SYNC_LDAP_URL"] == "ldap://ldap.example.com:389"
        assert additional_props["SYNC_LDAP_BIND_DN"] == "cn=admin,dc=example,dc=com"
        assert additional_props["SYNC_LDAP_BIND_PASSWORD"] == "ldap-secret-password"
        assert additional_props["SYNC_LDAP_SEARCH_BASE"] == "ou=users,dc=example,dc=com"
        assert (
            additional_props["SYNC_LDAP_USER_SEARCH_BASE"]
            == "ou=users,dc=example,dc=com"
        )
        assert additional_props["SYNC_LDAP_USER_SEARCH_FILTER"] == "(uid=*)"
        assert additional_props["SYNC_LDAP_USER_NAME_ATTRIBUTE"] == "uid"
        assert (
            additional_props["SYNC_GROUP_SEARCH_BASE"] == "ou=groups,dc=example,dc=com"
        )
        assert additional_props["SYNC_GROUP_SEARCH_FILTER"] == "(member=*)"
        assert additional_props["SYNC_GROUP_MEMBER_ATTRIBUTE_NAME"] == "member"
        assert additional_props["SYNC_GROUP_OBJECT_CLASS"] == "groupofnames"
        assert additional_props["SYNC_GROUP_NAME_ATTRIBUTE"] == "cn"
        assert additional_props["SYNC_LDAP_DELTASYNC"] == "false"
        assert additional_props["SYNC_LDAP_REFERRAL"] == "ignore"


@pytest.mark.asyncio
async def test_ranger_poll_status_with_ingress_domain(mock_service_dependencies):
    """Test that poll_status sets the correct ranger_url when ingress_domain is configured"""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    svc._resolve_namespace = AsyncMock(return_value="ranger-ns")
    svc.kubeconfig = AsyncMock(return_value="dummy-kubeconfig")
    svc.platform_state = AsyncMock(return_value=MagicMock(active=True))
    svc.project = AsyncMock(return_value=MagicMock(ingress_domain="example.com"))

    model = RangerPlatform(
        id=1,
        name="ranger-instance",
        title="Ranger Instance",
        project_id=1,
        database_id=10,
    )

    node_ports = []
    cluster_nodes = []

    with patch(
        "mindweaver.platform_service.ranger.service.asyncio.to_thread"
    ) as mock_to_thread:
        mock_to_thread.return_value = (
            "online",
            "Healthy",
            {"argo": "ok"},
            node_ports,
            cluster_nodes,
        )

        await svc.poll_status(model)

        state = await svc.platform_state(model)
        assert state.ranger_url == "https://ranger-instance.example.com"
        assert state.extra_data["ingress_domain"] == "example.com"


@pytest.mark.asyncio
async def test_ranger_envoy_route_rendering(mock_service_dependencies):
    """Test that Envoy Gateway HTTPRoute and BackendTLSPolicy are rendered for Ranger when ingress_domain is set"""
    import yaml

    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)
    svc._resolve_namespace = AsyncMock(return_value="ranger-ns")

    model = RangerPlatform(
        name="ranger-envoy",
        title="Ranger Envoy",
        project_id=1,
        database_id=10,
    )

    # Mock project with ingress_domain
    mock_project = MagicMock()
    mock_project.ingress_domain = "myproject.local"
    mock_project.ldap_config_id = None
    svc.project = AsyncMock(return_value=mock_project)

    # Mock PgSql
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ):
        manifest = await svc.render_manifests(model)

    docs = list(yaml.safe_load_all(manifest))

    # Verify HTTPRoute is present
    route = next(d for d in docs if d.get("kind") == "HTTPRoute")
    assert route["metadata"]["name"] == "ranger-envoy-route"
    assert route["spec"]["parentRefs"][0]["name"] == "project-gateway"
    assert route["spec"]["hostnames"][0] == "ranger-envoy.myproject.local"
    assert route["spec"]["rules"][0]["backendRefs"][0]["name"] == "ranger-envoy"
    assert route["spec"]["rules"][0]["backendRefs"][0]["port"] == 6080

    # Verify BackendTLSPolicy is present
    tls_policy = next(d for d in docs if d.get("kind") == "BackendTLSPolicy")
    assert tls_policy["metadata"]["name"] == "ranger-envoy-tls-policy"
    assert tls_policy["spec"]["targetRefs"][0]["name"] == "ranger-envoy"
    assert (
        tls_policy["spec"]["validation"]["hostname"]
        == "ranger-envoy.ranger-ns.svc.cluster.local"
    )
    assert (
        tls_policy["spec"]["validation"]["caCertificateRefs"][0]["name"]
        == "ranger-envoy-tls"
    )


@pytest.mark.asyncio
async def test_ranger_render_manifests_with_solr_initcontainer(
    mock_service_dependencies,
):
    """Test that rendered manifests include the ranger_audits init container when solr_id is set."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        solr_id=200,
        admin_password="admin",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    mock_project.ingress_domain = None
    svc.project = AsyncMock(return_value=mock_project)

    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    mock_solr_svc = AsyncMock()
    mock_solr_model = MagicMock()
    mock_solr_model.name = "test-solr"
    mock_solr_svc.get.return_value = mock_solr_model
    mock_solr_svc._resolve_namespace = AsyncMock(return_value="solr-ns")
    mock_solr_state = MagicMock()
    mock_solr_state.active = True
    mock_solr_state.admin_password = "solr-admin-pass"
    mock_solr_state.solr_user_password = "solr-user-pass"
    mock_solr_state.solr_internal_url = (
        "https://test-solr-solrcloud-headless.solr-ns.svc.cluster.local:8983"
    )
    mock_solr_svc.platform_state.return_value = mock_solr_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.SolrPlatformService.get_service",
        AsyncMock(return_value=mock_solr_svc),
    ), patch(
        "mindweaver.platform_service.ranger.service.decrypt_password",
        side_effect=lambda x: x,
    ):
        manifest = await svc.render_manifests(model)

    # Init container must be present
    assert "create-ranger-audits-collection" in manifest
    # Must reference the correct Solr internal URL
    assert (
        "https://test-solr-solrcloud-headless.solr-ns.svc.cluster.local:8983"
        in manifest
    )
    # Must reference the ranger_audits collection name
    assert "ranger_audits" in manifest
    # Must use admin credentials from admin_password
    assert "solr-admin-pass" in manifest
    # Must use curl with -k for self-signed TLS
    assert "curl -sk" in manifest
    # Must check if already configured
    assert (
        'if echo "${AUTH_CONFIG}" | grep -A 5 \'"name":"update"\' | grep -q \'"users"\'; then'
        in manifest
    )
    # Must update global update permission to allow users role
    assert (
        '\'{"update-permission": {"index": 10, "name": "update", "role": ["admin", "users"]}}\''
        in manifest
    )


@pytest.mark.asyncio
async def test_ranger_render_manifests_no_solr_no_initcontainer(
    mock_service_dependencies,
):
    """Test that no init container is rendered when solr_id is not set."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        admin_password="admin",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    mock_project = MagicMock()
    mock_project.ldap_config_id = None
    mock_project.ingress_domain = None
    svc.project = AsyncMock(return_value=mock_project)

    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    with patch(
        "mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service",
        AsyncMock(return_value=mock_pgsql_svc),
    ):
        manifest = await svc.render_manifests(model)

    # Init container must NOT be present when no Solr is linked
    assert "create-ranger-audits-collection" not in manifest
    assert "initContainers" not in manifest
