# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from fastapi import Request
from mindweaver.platform_service.ranger import RangerPlatform, RangerPlatformService
from mindweaver.fw.model import AsyncSession
from pydantic import ValidationError


@pytest.fixture
def mock_service_dependencies():
    request = MagicMock(spec=Request)
    session = MagicMock(spec=AsyncSession)
    session.exec = AsyncMock()
    return request, session


def test_ranger_resource_defaults():
    """Test default values for Ranger resource limits"""
    model = RangerPlatform(name="test-ranger", title="Test Ranger", project_id=1, database_id=10)
    assert model.cpu_request == 1.0
    assert model.cpu_limit == 2.0
    assert model.mem_request == 2.0
    assert model.mem_limit == 4.0
    assert model.opensearch_id is None


def test_ranger_validation():
    """Test validation logic for Ranger"""
    # Invalid CPU: request > limit
    with pytest.raises(ValidationError) as excinfo:
        RangerPlatform.model_validate(
            {
                "name": "test-ranger",
                "title": "Test Ranger",
                "project_id": 1,
                "database_id": 10,
                "cpu_request": 3.0,
                "cpu_limit": 2.0,
            }
        )
    assert "CPU request cannot be greater than CPU limit" in str(excinfo.value)


@pytest.mark.asyncio
async def test_ranger_template_vars(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        s3_storage_id=100,
        admin_password="admin",
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock PgSqlPlatformService
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # S3 Configuration Check
    mock_s3_svc = AsyncMock()
    mock_s3_model = MagicMock()
    mock_s3_model.endpoint_url = "http://s3.local"
    mock_s3_model.region = "us-east-1"
    mock_s3_model.access_key = "access"
    mock_s3_model.secret_key = "secret"
    mock_s3_svc.get.return_value = mock_s3_model

    with patch("mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service", AsyncMock(return_value=mock_pgsql_svc)), \
         patch("mindweaver.platform_service.ranger.service.S3StorageService.get_service", AsyncMock(return_value=mock_s3_svc)):
        
        # Test with default audit_s3_uri (s3://ranger/audit)
        vars = await svc.template_vars(model)
        
        assert vars["name"] == "test-ranger"
        assert vars["db_host"] == "test-db-pooler-rw.test-ns.svc.cluster.local"
        assert vars["db_user"] == "user"
        assert vars["db_pass"] == "pass"
        # s3://ranger/audit -> s3a://ranger/audit + /model.name
        assert vars["audit_hdfs_dest_dir"] == "s3a://ranger/audit/test-ranger"
        assert vars["admin_password"] == "admin"

        # Test with additional_properties
        model.additional_properties = {"ranger.test.prop": "value1", "another.prop": "value2"}
        vars = await svc.template_vars(model)
        assert vars["additional_properties"] == {"ranger.test.prop": "value1", "another.prop": "value2"}

        # Test with custom audit_s3_uri
        model.audit_s3_uri = "s3://my-bucket/my/path"
        vars = await svc.template_vars(model)
        assert vars["audit_hdfs_dest_dir"] == "s3a://my-bucket/my/path/test-ranger"


@pytest.mark.asyncio
async def test_ranger_password_generation(mock_service_dependencies):
    """Test that passwords are autogenerated during creation"""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
    )

    # Initial passwords should be None (after user removed defaults)
    assert model.admin_password is None

    # Trigger before_create hook
    await svc.generate_passwords(model)

    # Passwords should now be generated
    assert model.admin_password != "rangerR0cks!"
    assert len(model.admin_password) == 18
    assert model.keyadmin_password != "rangerR0cks!"
    assert len(model.keyadmin_password) == 18
    assert model.tagsync_password != "rangerR0cks!"
    assert len(model.tagsync_password) == 18
    assert model.usersync_password != "rangerR0cks!"
    assert len(model.usersync_password) == 18

    # Check complexity (at least one of each)
    import string

    def check_complexity(p):
        has_lower = any(c in string.ascii_lowercase for c in p)
        has_upper = any(c in string.ascii_uppercase for c in p)
        has_digit = any(c in string.digits for c in p)
        # Support both URI-safe and legacy symbols
        symbols = "!@#$%^&*()_+-=[]{}|;:,.<>?-_.~"
        has_symbol = any(c in symbols for c in p)
        return has_lower and has_upper and has_digit and has_symbol

    assert check_complexity(model.admin_password)
    assert check_complexity(model.keyadmin_password)
    assert check_complexity(model.tagsync_password)
    assert check_complexity(model.usersync_password)


@pytest.mark.asyncio
async def test_ranger_invalid_db(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    # Mock PgSql as inactive
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = False
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state
    
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    with patch("mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service", AsyncMock(return_value=mock_pgsql_svc)):
        with pytest.raises(ValueError, match="is not active"):
            await svc.template_vars(model)


@pytest.mark.asyncio
async def test_ranger_render_manifests(mock_service_dependencies):
    """Test that Ranger manifests render correct additional properties for limiting service-defs"""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        admin_password="admin",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    with patch("mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service", AsyncMock(return_value=mock_pgsql_svc)):
        # Default behavior: policymgr_supportedcomponents should be rendered
        manifests = await svc.render_manifests(model)
        assert "policymgr_supportedcomponents: trino,kafka,elasticsearch,nifi" in manifests
        assert "ranger.supportedcomponents: trino,kafka,elasticsearch,nifi" in manifests

        # Custom override in additional_properties
        model.additional_properties = {
            "policymgr_supportedcomponents": "kafka,trino",
            "ranger.supportedcomponents": "kafka,trino",
            "custom.property": "value"
        }
        manifests_custom = await svc.render_manifests(model)
        assert "policymgr_supportedcomponents: kafka,trino" in manifests_custom
        assert "ranger.supportedcomponents: kafka,trino" in manifests_custom
        assert "custom.property: value" in manifests_custom
        # Ensure default list doesn't appear when overridden
        assert "policymgr_supportedcomponents: trino,kafka,elasticsearch,nifi" not in manifests_custom


@pytest.mark.asyncio
async def test_ranger_template_vars_with_opensearch(mock_service_dependencies):
    """Test that template_vars properly constructs OpenSearch properties when opensearch_id is provided."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        opensearch_id=200,
        admin_password="admin",
    )

    # Mock _resolve_namespace
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock PgSqlPlatformService
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_state.db_user = "user"
    mock_pgsql_state.db_name = "ranger"
    mock_pgsql_state.db_pass = "pass"
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # Mock OpenSearchPlatformService
    mock_os_svc = AsyncMock()
    mock_os_model = MagicMock()
    mock_os_model.name = "test-os"
    mock_os_svc.get.return_value = mock_os_model
    mock_os_svc._resolve_namespace = AsyncMock(return_value="os-ns")
    
    mock_os_state = MagicMock()
    mock_os_state.active = True
    mock_os_state.opensearch_url = "https://test-os.os-ns.svc.cluster.local:9200"
    mock_os_state.admin_password = "os-password"
    mock_os_svc.platform_state.return_value = mock_os_state

    with patch("mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service", AsyncMock(return_value=mock_pgsql_svc)), \
         patch("mindweaver.platform_service.ranger.service.OpenSearchPlatformService.get_service", AsyncMock(return_value=mock_os_svc)):
        
        vars = await svc.template_vars(model)
        
        assert vars["name"] == "test-ranger"
        assert vars["db_host"] == "test-db-pooler-rw.test-ns.svc.cluster.local"
        assert vars["additional_properties"]["audit_store"] == "elasticsearch"
        assert vars["additional_properties"]["audit_elasticsearch_urls"] == "test-os.os-ns.svc.cluster.local"
        assert vars["additional_properties"]["audit_elasticsearch_port"] == "9200"
        assert vars["additional_properties"]["audit_elasticsearch_protocol"] == "https"
        assert vars["additional_properties"]["audit_elasticsearch_user"] == "admin"
        assert vars["additional_properties"]["audit_elasticsearch_password"] == "os-password"


@pytest.mark.asyncio
async def test_ranger_invalid_opensearch(mock_service_dependencies):
    """Test that template_vars raises ValueError if the associated OpenSearch instance is inactive."""
    request, session = mock_service_dependencies
    svc = RangerPlatformService(request, session)

    model = RangerPlatform(
        name="test-ranger",
        project_id=1,
        database_id=10,
        opensearch_id=200,
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock PgSql
    mock_pgsql_svc = AsyncMock()
    mock_pgsql_model = MagicMock()
    mock_pgsql_model.name = "test-db"
    mock_pgsql_svc.get.return_value = mock_pgsql_model
    mock_pgsql_state = MagicMock()
    mock_pgsql_state.active = True
    mock_pgsql_svc.platform_state.return_value = mock_pgsql_state

    # Mock OpenSearch as inactive
    mock_os_svc = AsyncMock()
    mock_os_model = MagicMock()
    mock_os_model.name = "test-os"
    mock_os_svc.get.return_value = mock_os_model
    mock_os_state = MagicMock()
    mock_os_state.active = False
    mock_os_svc.platform_state.return_value = mock_os_state

    with patch("mindweaver.platform_service.ranger.service.PgSqlPlatformService.get_service", AsyncMock(return_value=mock_pgsql_svc)), \
         patch("mindweaver.platform_service.ranger.service.OpenSearchPlatformService.get_service", AsyncMock(return_value=mock_os_svc)):
        with pytest.raises(ValueError, match="is not active"):
            await svc.template_vars(model)

