# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV0
    {{- if .Values.image }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    {{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: {{ .Values.fullnameOverride }}-tls
            certificate: tls.crt
            key: tls.key
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: {{ .Values.fullnameOverride }}-tls
            certificate: tls.crt
            key: tls.key
    config:
      offsets.topic.replication.factor: {{ .Values.controller.replicaCount }}
      transaction.state.log.replication.factor: {{ .Values.controller.replicaCount }}
      transaction.state.log.min.isr: 1
      default.replication.factor: {{ .Values.controller.replicaCount }}
      min.insync.replicas: 1
      inter.broker.protocol.version: "4.0"
    resources:
      requests:
        cpu: "{{ .Values.controller.resources.requests.cpu }}"
        memory: "{{ .Values.controller.resources.requests.memory }}"
      limits:
        cpu: "{{ .Values.controller.resources.limits.cpu }}"
        memory: "{{ .Values.controller.resources.limits.memory }}"
    {{- if .Values.extraEnvVars }}
    template:
      pod:
        env:
          {{- toYaml .Values.extraEnvVars | nindent 10 }}
    {{- end }}
