# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.fullnameOverride }}-pool
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.fullnameOverride }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.controller.persistence.size }}
        deleteClaim: true
