apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ranger.fullname" . }}-passwords
  labels:
    {{- include "ranger.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
  db-root-password: {{ .Values.db.rootPassword | b64enc | quote }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
  keyadmin-password: {{ .Values.admin.keyadminPassword | b64enc | quote }}
  tagsync-password: {{ .Values.admin.tagsyncPassword | b64enc | quote }}
  usersync-password: {{ .Values.admin.usersyncPassword | b64enc | quote }}
