# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import pytest
import string
from unittest.mock import MagicMock, AsyncMock, patch
from fastapi import Request
from pydantic import ValidationError
from mindweaver.platform_service.opensearch import OpenSearchPlatform, OpenSearchPlatformService
from mindweaver.fw.model import AsyncSession


@pytest.fixture
def mock_service_dependencies():
    request = MagicMock(spec=Request)
    session = MagicMock(spec=AsyncSession)
    session.exec = AsyncMock()
    session.flush = AsyncMock()
    return request, session


def test_opensearch_resource_defaults():
    """Test default values for OpenSearch resource limits and replicas"""
    model = OpenSearchPlatform(name="test-os", title="Test OpenSearch", project_id=1)
    assert model.replica_count == 1
    assert model.storage_size == "10Gi"
    assert model.cpu_request == 1.0
    assert model.cpu_limit == 2.0
    assert model.mem_request == 2.0
    assert model.mem_limit == 4.0


def test_opensearch_validation():
    """Test validation logic for OpenSearch CPU request vs limit and replica count"""
    # CPU invalid case
    with pytest.raises(ValidationError) as excinfo:
        OpenSearchPlatform.model_validate(
            {
                "name": "test-os",
                "title": "Test OpenSearch",
                "project_id": 1,
                "cpu_request": 3.0,
                "cpu_limit": 2.0,
            }
        )
    assert "CPU request cannot be greater than CPU limit" in str(excinfo.value)

    # Valid odd replica count cases
    for valid_replicas in [1, 3, 5, 7, 9]:
        model = OpenSearchPlatform.model_validate(
            {
                "name": "test-os",
                "title": "Test OpenSearch",
                "project_id": 1,
                "replica_count": valid_replicas,
            }
        )
        assert model.replica_count == valid_replicas

    # Invalid even/out of range replica count cases
    for invalid_replicas in [0, 2, 4, 6, 8, 10, 11]:
        with pytest.raises(ValidationError) as excinfo:
            OpenSearchPlatform.model_validate(
                {
                    "name": "test-os",
                    "title": "Test OpenSearch",
                    "project_id": 1,
                    "replica_count": invalid_replicas,
                }
            )
        assert "Replica count must be an odd number between 1 and 9" in str(excinfo.value)


@pytest.mark.asyncio
async def test_opensearch_template_vars(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="test-os",
        project_id=1,
        admin_password="my-admin-password",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")
    svc.project = AsyncMock(return_value=MagicMock(ingress_domain=None))

    # Resolve variables
    vars = await svc.template_vars(model)
    
    assert vars["name"] == "test-os"
    assert vars["namespace"] == "test-ns"
    assert vars["admin_password"] == "my-admin-password"
    assert vars["replica_count"] == 1
    assert "admin_password_hash" in vars
    # Deterministic salt should output a consistent hash starting with $2a$12$
    assert vars["admin_password_hash"].startswith("$2a$12$MindweaverDefaultSalte")


@pytest.mark.asyncio
async def test_opensearch_password_generation(mock_service_dependencies):
    """Test that OpenSearch admin passwords are autogenerated with proper complexity"""
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="test-os",
        project_id=1,
    )

    assert model.admin_password is None

    # Trigger password generation
    await svc.generate_passwords(model)

    assert model.admin_password is not None
    assert len(model.admin_password) == 18

    # Verify complexity
    def check_complexity(p):
        has_lower = any(c in string.ascii_lowercase for c in p)
        has_upper = any(c in string.ascii_uppercase for c in p)
        has_digit = any(c in string.digits for c in p)
        symbols = "-_.~!@#$%^&*()_+-=[]{}|;:,.<>?"
        has_symbol = any(c in symbols for c in p)
        return has_lower and has_upper and has_digit and has_symbol

    assert check_complexity(model.admin_password)


@pytest.mark.asyncio
async def test_opensearch_render_manifests(mock_service_dependencies):
    """Test that manifests render correctly for single node and multi node setups"""
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    # 1. Single node case
    model_single = OpenSearchPlatform(
        name="os-single",
        project_id=1,
        replica_count=1,
        admin_password="pass",
    )
    svc._resolve_namespace = AsyncMock(return_value="test-ns")
    svc.project = AsyncMock(return_value=MagicMock(ingress_domain=None))

    manifests_single = await svc.render_manifests(model_single)
    assert "singleNode: true" in manifests_single
    assert "replicas: 1" in manifests_single
    assert "OPENSEARCH_INITIAL_ADMIN_PASSWORD" in manifests_single
    assert 'value: "pass"' in manifests_single
    
    # Assert security-config Secret is rendered
    assert "kind: Secret" in manifests_single
    assert "name: os-single-security-config" in manifests_single
    assert "internal_users.yml" in manifests_single
    
    # Assert admin certificate is rendered
    assert "name: os-single-admin-tls" in manifests_single
    
    # Assert secret mount and subPath are rendered in the application manifest
    assert "name: os-single-security-config" in manifests_single
    assert "subPath: internal_users.yml" in manifests_single
    assert "path: /usr/share/opensearch/config/opensearch-security/internal_users.yml" in manifests_single
    assert "name: os-single-admin-tls" in manifests_single
    assert "path: /usr/share/opensearch/config/admin-certificates" in manifests_single

    # 2. Multi node scale case
    model_multi = OpenSearchPlatform(
        name="os-multi",
        project_id=1,
        replica_count=3,
        admin_password="pass",
    )
    manifests_multi = await svc.render_manifests(model_multi)
    assert "singleNode: false" in manifests_multi
    assert "replicas: 3" in manifests_multi


@pytest.mark.asyncio
async def test_opensearch_ingress_rendering(mock_service_dependencies):
    """Test that Envoy Gateway HTTPRoute and BackendTLSPolicy are rendered when ingress_domain is set"""
    import yaml
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="os-test",
        project_id=1,
        replica_count=1,
        admin_password="pass",
    )
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Mock project relationship
    mock_project = MagicMock()
    mock_project.ingress_domain = "132.home.kagesenshi.org"
    svc.project = AsyncMock(return_value=mock_project)

    manifests = await svc.render_manifests(model)
    docs = [d for d in yaml.safe_load_all(manifests) if d is not None]

    # Verify HTTPRoute is rendered
    route_doc = next(d for d in docs if d.get("kind") == "HTTPRoute")
    assert route_doc["metadata"]["name"] == "os-test-route"
    assert route_doc["spec"]["hostnames"] == ["os-test.132.home.kagesenshi.org"]
    assert route_doc["spec"]["rules"][0]["backendRefs"][0]["name"] == "os-test-cluster-master"
    assert route_doc["spec"]["rules"][0]["backendRefs"][0]["port"] == 9200

    # Verify BackendTLSPolicy is rendered
    policy_doc = next(d for d in docs if d.get("kind") == "BackendTLSPolicy")
    assert policy_doc["metadata"]["name"] == "os-test-tls-policy"
    assert policy_doc["spec"]["targetRefs"][0]["name"] == "os-test-cluster-master"
    assert policy_doc["spec"]["validation"]["caCertificateRefs"][0]["name"] == "os-test-tls"
    assert policy_doc["spec"]["validation"]["hostname"] == "os-test-cluster-master.test-ns.svc.cluster.local"


@pytest.mark.asyncio
async def test_opensearch_poll_status_ingress(mock_service_dependencies):
    """Test that opensearch_url is derived via ingress_domain in poll_status"""
    from mindweaver.platform_service.opensearch.model import OpenSearchPlatformState
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="os-test",
        project_id=1,
    )

    mock_state = MagicMock(spec=OpenSearchPlatformState)
    mock_state.active = True

    with patch.object(svc, "platform_state", AsyncMock(return_value=mock_state)), \
         patch.object(svc, "kubeconfig", AsyncMock(return_value="mock-kubeconfig")), \
         patch.object(svc, "_resolve_namespace", AsyncMock(return_value="test-ns")):

        node_ports = [{"name": "os-test", "port": 9200, "node_port": 30001}]
        cluster_nodes = [{"hostname": "node1", "ipv4": "1.2.3.4", "ipv6": None}]

        async def mock_poll(*args):
            return "online", "Healthy", {}, node_ports, cluster_nodes, "os-test-cluster-master"

        with patch("mindweaver.platform_service.opensearch.service.asyncio.to_thread", side_effect=mock_poll), \
             patch("mindweaver.platform_service.opensearch.service.decrypt_password", side_effect=lambda x: x):
            
            # 1. Test without ingress_domain (should derive NodePort URL)
            mock_project_no_ingress = MagicMock()
            mock_project_no_ingress.ingress_domain = None
            svc.project = AsyncMock(return_value=mock_project_no_ingress)

            await svc.poll_status(model)
            assert mock_state.opensearch_url == "https://1.2.3.4:30001"

            # 2. Test with ingress_domain (should derive secure Ingress URL)
            mock_project_ingress = MagicMock()
            mock_project_ingress.ingress_domain = "132.home.kagesenshi.org"
            svc.project = AsyncMock(return_value=mock_project_ingress)

            await svc.poll_status(model)
            assert mock_state.opensearch_url == "https://os-test.132.home.kagesenshi.org"
            assert mock_state.opensearch_url_ipv6 is None
            assert mock_state.extra_data["ingress_domain"] == "132.home.kagesenshi.org"


