# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import pytest
import string
from unittest.mock import MagicMock, AsyncMock, patch
from fastapi import Request
from pydantic import ValidationError
from mindweaver.platform_service.opensearch import OpenSearchPlatform, OpenSearchPlatformService
from mindweaver.fw.model import AsyncSession


@pytest.fixture
def mock_service_dependencies():
    request = MagicMock(spec=Request)
    session = MagicMock(spec=AsyncSession)
    session.exec = AsyncMock()
    return request, session


def test_opensearch_resource_defaults():
    """Test default values for OpenSearch resource limits and replicas"""
    model = OpenSearchPlatform(name="test-os", title="Test OpenSearch", project_id=1)
    assert model.replica_count == 1
    assert model.storage_size == "10Gi"
    assert model.cpu_request == 1.0
    assert model.cpu_limit == 2.0
    assert model.mem_request == 2.0
    assert model.mem_limit == 4.0


def test_opensearch_validation():
    """Test validation logic for OpenSearch CPU request vs limit and replica count"""
    # CPU invalid case
    with pytest.raises(ValidationError) as excinfo:
        OpenSearchPlatform.model_validate(
            {
                "name": "test-os",
                "title": "Test OpenSearch",
                "project_id": 1,
                "cpu_request": 3.0,
                "cpu_limit": 2.0,
            }
        )
    assert "CPU request cannot be greater than CPU limit" in str(excinfo.value)

    # Valid odd replica count cases
    for valid_replicas in [1, 3, 5, 7, 9]:
        model = OpenSearchPlatform.model_validate(
            {
                "name": "test-os",
                "title": "Test OpenSearch",
                "project_id": 1,
                "replica_count": valid_replicas,
            }
        )
        assert model.replica_count == valid_replicas

    # Invalid even/out of range replica count cases
    for invalid_replicas in [0, 2, 4, 6, 8, 10, 11]:
        with pytest.raises(ValidationError) as excinfo:
            OpenSearchPlatform.model_validate(
                {
                    "name": "test-os",
                    "title": "Test OpenSearch",
                    "project_id": 1,
                    "replica_count": invalid_replicas,
                }
            )
        assert "Replica count must be an odd number between 1 and 9" in str(excinfo.value)


@pytest.mark.asyncio
async def test_opensearch_template_vars(mock_service_dependencies):
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="test-os",
        project_id=1,
        admin_password="my-admin-password",
    )

    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    # Resolve variables
    vars = await svc.template_vars(model)
    
    assert vars["name"] == "test-os"
    assert vars["namespace"] == "test-ns"
    assert vars["admin_password"] == "my-admin-password"
    assert vars["replica_count"] == 1
    assert "admin_password_hash" in vars
    # Deterministic salt should output a consistent hash starting with $2a$12$
    assert vars["admin_password_hash"].startswith("$2a$12$MindweaverDefaultSalte")


@pytest.mark.asyncio
async def test_opensearch_password_generation(mock_service_dependencies):
    """Test that OpenSearch admin passwords are autogenerated with proper complexity"""
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    model = OpenSearchPlatform(
        name="test-os",
        project_id=1,
    )

    assert model.admin_password is None

    # Trigger password generation
    await svc.generate_passwords(model)

    assert model.admin_password is not None
    assert len(model.admin_password) == 18

    # Verify complexity
    def check_complexity(p):
        has_lower = any(c in string.ascii_lowercase for c in p)
        has_upper = any(c in string.ascii_uppercase for c in p)
        has_digit = any(c in string.digits for c in p)
        symbols = "-_.~!@#$%^&*()_+-=[]{}|;:,.<>?"
        has_symbol = any(c in symbols for c in p)
        return has_lower and has_upper and has_digit and has_symbol

    assert check_complexity(model.admin_password)


@pytest.mark.asyncio
async def test_opensearch_render_manifests(mock_service_dependencies):
    """Test that manifests render correctly for single node and multi node setups"""
    request, session = mock_service_dependencies
    svc = OpenSearchPlatformService(request, session)

    # 1. Single node case
    model_single = OpenSearchPlatform(
        name="os-single",
        project_id=1,
        replica_count=1,
        admin_password="pass",
    )
    svc._resolve_namespace = AsyncMock(return_value="test-ns")

    manifests_single = await svc.render_manifests(model_single)
    assert "singleNode: true" in manifests_single
    assert "replicas: 1" in manifests_single
    assert "OPENSEARCH_INITIAL_ADMIN_PASSWORD" in manifests_single
    assert 'value: "pass"' in manifests_single
    
    # Assert security-config Secret is rendered
    assert "kind: Secret" in manifests_single
    assert "name: os-single-security-config" in manifests_single
    assert "internal_users.yml" in manifests_single
    
    # Assert admin certificate is rendered
    assert "name: os-single-admin-tls" in manifests_single
    
    # Assert secret mount and subPath are rendered in the application manifest
    assert "name: os-single-security-config" in manifests_single
    assert "subPath: internal_users.yml" in manifests_single
    assert "path: /usr/share/opensearch/config/opensearch-security/internal_users.yml" in manifests_single
    assert "name: os-single-admin-tls" in manifests_single
    assert "path: /usr/share/opensearch/config/admin-certificates" in manifests_single

    # 2. Multi node scale case
    model_multi = OpenSearchPlatform(
        name="os-multi",
        project_id=1,
        replica_count=3,
        admin_password="pass",
    )
    manifests_multi = await svc.render_manifests(model_multi)
    assert "singleNode: false" in manifests_multi
    assert "replicas: 3" in manifests_multi

