# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

apiVersion: v2
name: kafka
description: A Helm chart to deploy Apache Kafka using Strimzi Custom Resource on Kubernetes
type: application
version: 0.1.1
appVersion: "4.0.0-rev.1"
