# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

fullnameOverride: "kafka"

image:
  repository: ghcr.io/kagesenshi/mindweaver/kafka
  pullPolicy: Always
  tag: "4.0.0-rev.1"

controller:
  replicaCount: 3
  resources:
    requests:
      cpu: 0.5
      memory: 1
    limits:
      cpu: 1.0
      memory: 2
  persistence:
    size: "20Gi"
