# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.fullnameOverride }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "update", "patch", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.fullnameOverride }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.fullnameOverride }}-leader-election-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterManager: kubernetes
  clusterImage: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        type: http
        name: http
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 6342
        type: load-balance
        name: load-balance
  service:
    headlessEnabled: true
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.cluster.leader.election.implementation=KubernetesLeaderElectionManager
        nifi.cluster.leader.election.kubernetes.lease.prefix={{ .Values.fullnameOverride }}
        nifi.sensitive.props.key={{ .Values.sensitivePropsKey }}
        nifi.web.http.host=0.0.0.0
        nifi.web.proxy.host=localhost:8080,127.0.0.1:8080,{{ .Values.fullnameOverride }}-headless.{{ .Release.Namespace }}.svc.cluster.local:8080,{{ .Values.fullnameOverride }}-0-node.{{ .Values.fullnameOverride }}-headless.{{ .Release.Namespace }}.svc.cluster.local:8080,{{ .Values.fullnameOverride }}-headless.{{ .Release.Namespace }}.svc:8080,{{ .Values.fullnameOverride }}-headless.{{ .Release.Namespace }}:8080,{{ .Values.fullnameOverride }}-headless:8080,{{ .Values.fullnameOverride }}-0-node:8080
    bootstrapProperties:
      overrideConfigs: |
        java.arg.addopens.exodus=--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
  nodes:
    {{- range $i := until (int .Values.replicaCount) }}
    - id: {{ $i }}
      nodeConfigGroup: default_group
    {{- end }}
  nodeConfigGroups:
    default_group:
      isNode: true
      serviceAccountName: {{ .Values.fullnameOverride }}-sa
      storageConfigs:
        - name: data
          mountPath: "/opt/nifi/nifi-current/data"
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            {{- if .Values.persistence.storageClassName }}
            storageClassName: "{{ .Values.persistence.storageClassName }}"
            {{- end }}
            resources:
              requests:
                storage: "{{ .Values.persistence.size }}"
      resourcesRequirements:
        requests:
          cpu: "{{ .Values.resources.requests.cpu }}"
          memory: "{{ .Values.resources.requests.memory }}"
        limits:
          cpu: "{{ .Values.resources.limits.cpu }}"
          memory: "{{ .Values.resources.limits.memory }}"
