# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import os
from apache_ranger.model.ranger_service import RangerService
from apache_ranger.client.ranger_client import RangerClient
from json import JSONDecodeError

import json
import urllib3
from apache_ranger.model.ranger_service_def import RangerServiceDef
from requests.exceptions import ConnectionError, SSLError

# Disable insecure request warnings for self-signed SSL certificates
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Read admin password from environment, fallback to rangerR0cks!
admin_password = os.environ.get("RANGER_ADMIN_PASSWORD", "rangerR0cks!")

# Attempt to discover the correct protocol and port (HTTPS vs HTTP, 6182 vs 6080)
ranger_client = None
for port in [6182, 6080]:
    for protocol in ['https', 'http']:
        url = f"{protocol}://localhost:{port}"
        try:
            client = RangerClient(url, ('admin', admin_password))
            client.session.verify = False
            # Perform a test call to verify connectivity
            client.get_service_def('tag')
            ranger_client = client
            print(f"Successfully connected to Ranger Admin using {url}")
            break
        except Exception as e:
            pass
    if ranger_client:
        break

if not ranger_client:
    print("Warning: Could not verify connection to Ranger Admin. Defaulting to default client configuration.")
    # Fallback default
    ranger_client = RangerClient('http://localhost:6080', ('admin', admin_password))
    ranger_client.session.verify = False


def update_usersync_password():
    """Update the rangerusersync password in Ranger Admin database via the REST API.
    
    This ensures that the rangerusersync account password matches the autogenerated/configured
    RANGER_USERSYNC_PASSWORD environment variable.
    """
    usersync_password = os.environ.get("RANGER_USERSYNC_PASSWORD")
    if not usersync_password:
        print("RANGER_USERSYNC_PASSWORD not set in environment, skipping password update.")
        return

    try:
        url = 'http://localhost:6080/service/xusers/secure/users'
        response = ranger_client.session.get(url, params={'name': 'rangerusersync'}, headers={'Accept': 'application/json'})
        if response.status_code != 200:
            print(f"Failed to get usersync user details: {response.status_code} {response.text}")
            return
        
        data = response.json()
        users = data.get('vXUsers', [])
        if not users:
            print("User rangerusersync not found in database.")
            return
            
        user = users[0]
        user_id = user.get('id')
        
        user['password'] = usersync_password
        user['status'] = 1
        
        put_url = f'http://localhost:6080/service/xusers/secure/users/{user_id}'
        put_response = ranger_client.session.put(put_url, json=user, headers={
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        })
        if put_response.status_code == 200:
            print("Successfully updated rangerusersync password in Ranger Admin!")
        else:
            print(f"Failed to update rangerusersync password: {put_response.status_code} {put_response.text}")
            
    except Exception as e:
        print(f"An exception occurred when updating rangerusersync password: {e}")

update_usersync_password()

