# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import os
from apache_ranger.model.ranger_service import RangerService
from apache_ranger.client.ranger_client import RangerClient
from json import JSONDecodeError

import json
from apache_ranger.model.ranger_service_def import RangerServiceDef

# Read admin password from environment, fallback to rangerR0cks!
admin_password = os.environ.get("RANGER_ADMIN_PASSWORD", "rangerR0cks!")

# Use localhost since it runs inside the container
ranger_client = RangerClient('http://localhost:6080', ('admin', admin_password))

def register_superset_servicedef():
    """Reads the superset service definition JSON and registers it in Ranger Admin."""
    servicedef_path = '/home/ranger/scripts/ranger-servicedef-superset.json'
    if not os.path.exists(servicedef_path):
        print(f"Service definition file not found: {servicedef_path}")
        return

    try:
        with open(servicedef_path, 'r') as f:
            servicedef_data = json.load(f)
        
        service_def_name = servicedef_data.get('name')
        try:
            existing = ranger_client.get_service_def(service_def_name)
        except Exception:
            existing = None

        if existing is None:
            service_def = RangerServiceDef(servicedef_data)
            ranger_client.create_service_def(service_def)
            print(f"Service definition '{service_def_name}' registered successfully!")
        else:
            print(f"Service definition '{service_def_name}' already exists.")
    except Exception as e:
        print(f"Failed to register service definition: {e}")

register_superset_servicedef()

def update_usersync_password():
    """Update the rangerusersync password in Ranger Admin database via the REST API.
    
    This ensures that the rangerusersync account password matches the autogenerated/configured
    RANGER_USERSYNC_PASSWORD environment variable.
    """
    usersync_password = os.environ.get("RANGER_USERSYNC_PASSWORD")
    if not usersync_password:
        print("RANGER_USERSYNC_PASSWORD not set in environment, skipping password update.")
        return

    try:
        url = 'http://localhost:6080/service/xusers/secure/users'
        response = ranger_client.session.get(url, params={'name': 'rangerusersync'}, headers={'Accept': 'application/json'})
        if response.status_code != 200:
            print(f"Failed to get usersync user details: {response.status_code} {response.text}")
            return
        
        data = response.json()
        users = data.get('vXUsers', [])
        if not users:
            print("User rangerusersync not found in database.")
            return
            
        user = users[0]
        user_id = user.get('id')
        
        user['password'] = usersync_password
        user['status'] = 1
        
        put_url = f'http://localhost:6080/service/xusers/secure/users/{user_id}'
        put_response = ranger_client.session.put(put_url, json=user, headers={
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        })
        if put_response.status_code == 200:
            print("Successfully updated rangerusersync password in Ranger Admin!")
        else:
            print(f"Failed to update rangerusersync password: {put_response.status_code} {put_response.text}")
            
    except Exception as e:
        print(f"An exception occurred when updating rangerusersync password: {e}")

update_usersync_password()

