# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

import os
from apache_ranger.model.ranger_service import RangerService
from apache_ranger.client.ranger_client import RangerClient
from json import JSONDecodeError

# Read admin password from environment, fallback to rangerR0cks!
admin_password = os.environ.get("RANGER_ADMIN_PASSWORD", "rangerR0cks!")

# Use localhost since it runs inside the container
ranger_client = RangerClient('http://localhost:6080', ('admin', admin_password))

def service_not_exists(service):
    try:
        svc = ranger_client.get_service(service.name)
    except JSONDecodeError:
        return 1
    return 0 if svc is not None else 1

kafka = RangerService({'name': 'dev_kafka', 'type': 'kafka',
                       'configs': {'username': 'kafka', 'password': 'kafka',
                                   'zookeeper.connect': 'ranger-zk.example.com:2181'}})

trino = RangerService({'name': 'dev_trino',
                       'type': 'trino',
                       'configs': {
                           'username': 'trino',
                           'password': 'trino',
                           'jdbc.driverClassName': 'io.trino.jdbc.TrinoDriver',
                           'jdbc.url': 'jdbc:trino://ranger-trino:8080',
                       }})

elasticsearch = RangerService({'name': 'dev_elasticsearch',
                               'type': 'elasticsearch',
                               'configs': {
                                   'username': 'elastic',
                                   'password': 'changeit',
                                   'elasticsearch.url': 'http://elasticsearch:9200',
                               }})

nifi = RangerService({'name': 'dev_nifi',
                      'type': 'nifi',
                      'configs': {
                          'username': 'admin',
                          'password': 'changeit',
                          'nifi.url': 'http://nifi:8080',
                      }})

# Only keep kafka, trino, elasticsearch, and nifi enabled
services = [kafka, trino, elasticsearch, nifi]
for service in services:
    try:
        if service_not_exists(service):
            ranger_client.create_service(service)
            print(f" {service.name} service created!")
    except Exception as e:
        print(f"An exception occurred when creating service {service.name}: {e}")

def update_usersync_password():
    """Update the rangerusersync password in Ranger Admin database via the REST API.
    
    This ensures that the rangerusersync account password matches the autogenerated/configured
    RANGER_USERSYNC_PASSWORD environment variable.
    """
    usersync_password = os.environ.get("RANGER_USERSYNC_PASSWORD")
    if not usersync_password:
        print("RANGER_USERSYNC_PASSWORD not set in environment, skipping password update.")
        return

    try:
        url = 'http://localhost:6080/service/xusers/secure/users'
        response = ranger_client.session.get(url, params={'name': 'rangerusersync'}, headers={'Accept': 'application/json'})
        if response.status_code != 200:
            print(f"Failed to get usersync user details: {response.status_code} {response.text}")
            return
        
        data = response.json()
        users = data.get('vXUsers', [])
        if not users:
            print("User rangerusersync not found in database.")
            return
            
        user = users[0]
        user_id = user.get('id')
        
        user['password'] = usersync_password
        user['status'] = 1
        
        put_url = f'http://localhost:6080/service/xusers/secure/users/{user_id}'
        put_response = ranger_client.session.put(put_url, json=user, headers={
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        })
        if put_response.status_code == 200:
            print("Successfully updated rangerusersync password in Ranger Admin!")
        else:
            print(f"Failed to update rangerusersync password: {put_response.status_code} {put_response.text}")
            
    except Exception as e:
        print(f"An exception occurred when updating rangerusersync password: {e}")

update_usersync_password()

