"""add central cert issuer

Revision ID: 014846ae7cfd
Revises: 872f647e1af6
Create Date: 2026-03-15 10:59:23.615418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '014846ae7cfd'
down_revision: Union[str, Sequence[str], None] = '872f647e1af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('cluster_issuer_installed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('mw_trino_platform', sa.Column('keystore_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("''")))
    op.alter_column('mw_trino_platform', 'internal_shared_secret',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_trino_platform', 'internal_shared_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mw_trino_platform', 'keystore_password')
    op.drop_column('mw_k8s_cluster_status', 'cluster_issuer_installed')
    # ### end Alembic commands ###
