# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add opensearch_id to ranger

Revision ID: 035cec8b1ae3
Revises: d763700c5c90
Create Date: 2026-05-24 07:13:54.621538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '035cec8b1ae3'
down_revision: Union[str, Sequence[str], None] = 'd763700c5c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ranger_platform', sa.Column('opensearch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_ranger_platform', 'mw_opensearch_platform', ['opensearch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_ranger_platform', type_='foreignkey')
    op.drop_column('mw_ranger_platform', 'opensearch_id')
    # ### end Alembic commands ###
