"""init

Revision ID: 0628a1b798f1
Revises: f7a9e21a59d4
Create Date: 2026-01-04 22:22:43.561402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0628a1b798f1'
down_revision: Union[str, Sequence[str], None] = 'f7a9e21a59d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_s3_storage', sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mw_s3_storage', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mw_s3_storage', sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mw_s3_storage', sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_s3_storage', sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_mw_s3_storage_bucket'), 'mw_s3_storage', ['bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_s3_storage_bucket'), table_name='mw_s3_storage')
    op.drop_column('mw_s3_storage', 'endpoint_url')
    op.drop_column('mw_s3_storage', 'secret_key')
    op.drop_column('mw_s3_storage', 'access_key')
    op.drop_column('mw_s3_storage', 'region')
    op.drop_column('mw_s3_storage', 'bucket')
    # ### end Alembic commands ###
