"""added ldap config

Revision ID: 10ad4a7ad73b
Revises: a6d4435f371a
Create Date: 2026-03-14 20:59:33.053848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '10ad4a7ad73b'
down_revision: Union[str, Sequence[str], None] = 'a6d4435f371a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_ldap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bind_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bind_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_search_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_search_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_search_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_search_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_member_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ldap_config_project_id'), 'mw_ldap_config', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_ldap_config_project_id'), table_name='mw_ldap_config')
    op.drop_table('mw_ldap_config')
    # ### end Alembic commands ###
