# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add disable_s3_cert_checking to hms

Revision ID: 16403e0ff382
Revises: ac220a11b9bf
Create Date: 2026-08-24 13:46:11.105832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '16403e0ff382'
down_revision: Union[str, Sequence[str], None] = 'ac220a11b9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_hive_metastore_platform', sa.Column('disable_s3_cert_checking', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_hive_metastore_platform', 'disable_s3_cert_checking')
    # ### end Alembic commands ###
