"""add envoy gateway service type to k8s cluster

Revision ID: 269a01e839a3
Revises: 6766b685948e
Create Date: 2026-06-01 10:43:58.675138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '269a01e839a3'
down_revision: Union[str, Sequence[str], None] = '6766b685948e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster', sa.Column('envoy_gateway_service_type', sa.Enum('LoadBalancer', 'NodePort', name='envoygatewayservicetype', native_enum=False), server_default='NodePort', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster', 'envoy_gateway_service_type')
    # ### end Alembic commands ###
