"""split_datasource

Revision ID: 285e72a8f941
Revises: feea26386696
Create Date: 2026-03-17 06:09:34.060898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '285e72a8f941'
down_revision: Union[str, Sequence[str], None] = 'feea26386696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_api_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_type', sa.String(length=50), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_api_source_project_id'), 'mw_api_source', ['project_id'], unique=False)
    op.create_table('mw_database_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=255), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_database_source_project_id'), 'mw_database_source', ['project_id'], unique=False)
    op.create_table('mw_streaming_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('broker_type', sa.String(length=50), nullable=False),
    sa.Column('bootstrap_servers', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_streaming_source_project_id'), 'mw_streaming_source', ['project_id'], unique=False)
    op.create_table('mw_web_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_web_source_project_id'), 'mw_web_source', ['project_id'], unique=False)

    # Data Migration Logic
    connection = op.get_bind()
    
    # Check if mw_datasource exists before trying to migrate
    inspector = sa.inspect(connection)
    if 'mw_datasource' in inspector.get_table_names():
        old_sources = connection.execute(sa.text("SELECT * FROM mw_datasource")).fetchall()
        
        # Map old ID to (new_table, new_id)
        # Note: We try to keep the IDs the same if possible to simplify Trino migration,
        # but since we are splitting into 3 tables, there might be conflicts if IDs overlap across types.
        # However, they were all in one table before, so their IDs are unique.
        # We can safely use the same IDs in new tables as long as we don't have existing data in new tables.
        
        db_sources = []
        web_sources = []
        api_sources = []
        
        id_to_type = {} # old_id -> type ('db', 'web', 'api')

        for row in old_sources:
            # Row access depends on version: row.id or row['id']
            # Using row._mapping for SQLAlchemy 1.4+ / 2.0
            r = row._mapping
            
            common = {
                'id': r['id'],
                'uuid': r['uuid'],
                'created': r['created'],
                'modified': r['modified'],
                'name': r['name'],
                'title': r['title'],
                'project_id': r['project_id'],
                'description': r['description'],
                'login': r['login'],
                'password': r['password'],
                'enable_ssl': r['enable_ssl'],
                'verify_ssl': r['verify_ssl'],
                'parameters': r['parameters']
            }
            
            driver = r['driver'].lower() if r['driver'] else ""
            if driver in ('postgresql', 'mysql', 'mariadb', 'trino', 'mssql', 'oracle', 'mongodb'):
                common.update({
                    'engine': driver,
                    'host': r['host'] or 'localhost',
                    'port': r['port'],
                    'database': r['resource']
                })
                db_sources.append(common)
                id_to_type[r['id']] = 'db'
            elif driver == 'web':
                # Attempt to construct URL if not present or use host
                url = r['host'] or ""
                if url and "://" not in url:
                    scheme = "https" if r['enable_ssl'] else "http"
                    url = f"{scheme}://{url}"
                    if r['resource']:
                        if not r['resource'].startswith("/"):
                            url += "/"
                        url += r['resource']
                
                common.update({
                    'url': url,
                    'allowed_domains': None,
                    'user_agent': None
                })
                web_sources.append(common)
                id_to_type[r['id']] = 'web'
            else:
                common.update({
                    'base_url': r['host'] or "",
                    'api_type': 'rest',
                    'auth_type': 'none'
                })
                api_sources.append(common)
                id_to_type[r['id']] = 'api'

        if db_sources:
            op.bulk_insert(sa.table('mw_database_source',
                sa.Column('id', sa.Integer()),
                sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType()),
                sa.Column('created', sa.DateTime(timezone=True)),
                sa.Column('modified', sa.DateTime(timezone=True)),
                sa.Column('name', sa.String()),
                sa.Column('title', sa.String()),
                sa.Column('project_id', sa.Integer()),
                sa.Column('description', sa.Text()),
                sa.Column('login', sa.String()),
                sa.Column('password', sa.String()),
                sa.Column('enable_ssl', sa.Boolean()),
                sa.Column('verify_ssl', sa.Boolean()),
                sa.Column('parameters', sqlalchemy_utils.types.json.JSONType()),
                sa.Column('engine', sa.String()),
                sa.Column('host', sa.String()),
                sa.Column('port', sa.Integer()),
                sa.Column('database', sa.String()),
                sa.Column('schema_name', sa.String()),
            ), db_sources)

        if web_sources:
            op.bulk_insert(sa.table('mw_web_source',
                sa.Column('id', sa.Integer()),
                sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType()),
                sa.Column('created', sa.DateTime(timezone=True)),
                sa.Column('modified', sa.DateTime(timezone=True)),
                sa.Column('name', sa.String()),
                sa.Column('title', sa.String()),
                sa.Column('project_id', sa.Integer()),
                sa.Column('description', sa.Text()),
                sa.Column('login', sa.String()),
                sa.Column('password', sa.String()),
                sa.Column('enable_ssl', sa.Boolean()),
                sa.Column('verify_ssl', sa.Boolean()),
                sa.Column('parameters', sqlalchemy_utils.types.json.JSONType()),
                sa.Column('url', sa.String()),
                sa.Column('allowed_domains', sa.Text()),
                sa.Column('user_agent', sa.String()),
            ), web_sources)

        if api_sources:
            op.bulk_insert(sa.table('mw_api_source',
                sa.Column('id', sa.Integer()),
                sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType()),
                sa.Column('created', sa.DateTime(timezone=True)),
                sa.Column('modified', sa.DateTime(timezone=True)),
                sa.Column('name', sa.String()),
                sa.Column('title', sa.String()),
                sa.Column('project_id', sa.Integer()),
                sa.Column('description', sa.Text()),
                sa.Column('login', sa.String()),
                sa.Column('password', sa.String()),
                sa.Column('enable_ssl', sa.Boolean()),
                sa.Column('verify_ssl', sa.Boolean()),
                sa.Column('parameters', sqlalchemy_utils.types.json.JSONType()),
                sa.Column('base_url', sa.String()),
                sa.Column('api_type', sa.String()),
                sa.Column('auth_type', sa.String()),
            ), api_sources)

        # Drop old table
        op.drop_table('mw_datasource')

    # Trino Platform Migration
    op.add_column('mw_trino_platform', sa.Column('database_source_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False, server_default='[]'))
    
    # Migrate data_source_ids to database_source_ids
    trino_platforms = connection.execute(sa.text("SELECT id, data_source_ids FROM mw_trino_platform")).fetchall()
    for tp in trino_platforms:
        r = tp._mapping
        old_ids = r['data_source_ids'] or []
        # Filter only those that became DatabaseSources
        new_ids = [oid for oid in old_ids if id_to_type.get(oid) == 'db']
        # JSON update in Postgres
        import json
        connection.execute(
            sa.text("UPDATE mw_trino_platform SET database_source_ids = :new_ids WHERE id = :id"),
            {"new_ids": json.dumps(new_ids), "id": r['id']}
        )

    op.drop_column('mw_trino_platform', 'data_source_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Downgrade is complex due to data loss risks, implementing basic schema changes
    op.add_column('mw_trino_platform', sa.Column('data_source_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default='[]'))
    op.drop_column('mw_trino_platform', 'database_source_ids')
    op.drop_index(op.f('ix_mw_web_source_project_id'), table_name='mw_web_source')
    op.drop_table('mw_web_source')
    op.drop_index(op.f('ix_mw_streaming_source_project_id'), table_name='mw_streaming_source')
    op.drop_table('mw_streaming_source')
    op.drop_index(op.f('ix_mw_database_source_project_id'), table_name='mw_database_source')
    op.drop_table('mw_database_source')
    op.drop_index(op.f('ix_mw_api_source_project_id'), table_name='mw_api_source')
    op.drop_table('mw_api_source')
    # ### end Alembic commands ###
