"""add process x-forwarded-for

Revision ID: 29624155aa48
Revises: ebf1b3b2e626
Create Date: 2026-04-28 07:54:33.930530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '29624155aa48'
down_revision: Union[str, Sequence[str], None] = 'ebf1b3b2e626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('process_forwarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_trino_platform', 'process_forwarded')
    # ### end Alembic commands ###
