# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add auth_role_mapping to nifi

Revision ID: 2de878822d04
Revises: 92b6d8b76342
Create Date: 2026-07-05 22:50:24.801582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2de878822d04'
down_revision: Union[str, Sequence[str], None] = '92b6d8b76342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_nifi_platform', sa.Column('auth_role_mapping', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_nifi_platform', 'auth_role_mapping')
    # ### end Alembic commands ###
