"""Add User table

Revision ID: 2e310e02cef2
Revises: 32d193b1654e
Create Date: 2026-01-01 23:51:55.243308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "2e310e02cef2"
down_revision: Union[str, Sequence[str], None] = "32d193b1654e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mw_user",
        sa.Column(
            "preferred_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "mw_user",
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "mw_user",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.drop_index(op.f("ix_mw_user_sub"), table_name="mw_user")
    op.drop_index(op.f("ix_mw_user_email"), table_name="mw_user")
    op.create_index(op.f("ix_mw_user_email"), "mw_user", ["email"], unique=True)
    op.drop_column("mw_user", "full_name")
    op.drop_column("mw_user", "sub")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mw_user", sa.Column("sub", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "mw_user",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_mw_user_email"), table_name="mw_user")
    op.create_index(op.f("ix_mw_user_email"), "mw_user", ["email"], unique=False)
    op.create_index(op.f("ix_mw_user_sub"), "mw_user", ["sub"], unique=True)
    op.drop_column("mw_user", "is_active")
    op.drop_column("mw_user", "display_name")
    op.drop_column("mw_user", "preferred_username")
    # ### end Alembic commands ###
