"""remove_ranger_and_solr

Revision ID: 30840d7c54af
Revises: da790bf871f1
Create Date: 2026-06-28 22:05:12.204996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30840d7c54af'
down_revision: Union[str, Sequence[str], None] = 'da790bf871f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop constraints and columns from mw_trino_platform
    op.drop_constraint('mw_trino_platform_ranger_id_fkey', 'mw_trino_platform', type_='foreignkey')
    op.drop_column('mw_trino_platform', 'ranger_user_password')
    op.drop_column('mw_trino_platform', 'ranger_id')

    # 2. Drop Ranger state table (depends on Ranger platform)
    op.drop_index(op.f('ix_mw_ranger_platform_state_platform_id'), table_name='mw_ranger_platform_state')
    op.drop_index(op.f('ix_mw_ranger_platform_state_status'), table_name='mw_ranger_platform_state')
    op.drop_table('mw_ranger_platform_state')

    # 3. Drop Ranger platform table
    op.drop_index(op.f('ix_mw_ranger_platform_project_id'), table_name='mw_ranger_platform')
    op.drop_table('mw_ranger_platform')

    # 4. Drop Solr state table (depends on Solr platform)
    op.drop_index(op.f('ix_mw_solr_platform_state_platform_id'), table_name='mw_solr_platform_state')
    op.drop_index(op.f('ix_mw_solr_platform_state_status'), table_name='mw_solr_platform_state')
    op.drop_table('mw_solr_platform_state')

    # 5. Drop Solr platform table
    op.drop_index(op.f('ix_mw_solr_platform_project_id'), table_name='mw_solr_platform')
    op.drop_table('mw_solr_platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('ranger_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mw_trino_platform', sa.Column('ranger_user_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mw_trino_platform_ranger_id_fkey'), 'mw_trino_platform', 'mw_ranger_platform', ['ranger_id'], ['id'])
    op.create_table('mw_ranger_platform_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('node_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cluster_nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ranger_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keyadmin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tagsync_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usersync_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ranger_url_ipv6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_ranger_platform.id'], name=op.f('mw_ranger_platform_state_platform_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_ranger_platform_state_pkey'))
    )
    op.create_index(op.f('ix_mw_ranger_platform_state_status'), 'mw_ranger_platform_state', ['status'], unique=False)
    op.create_index(op.f('ix_mw_ranger_platform_state_platform_id'), 'mw_ranger_platform_state', ['platform_id'], unique=False)
    op.create_table('mw_solr_platform',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mw_solr_platform_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replica_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpu_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cpu_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name='mw_solr_platform_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mw_solr_platform_pkey'),
    sa.UniqueConstraint('name', name='mw_solr_platform_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_mw_solr_platform_project_id'), 'mw_solr_platform', ['project_id'], unique=False)
    op.create_table('mw_solr_platform_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('node_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cluster_nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('solr_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('solr_url_ipv6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('k8s_oper_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('solr_user_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('solr_internal_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_solr_platform.id'], name=op.f('mw_solr_platform_state_platform_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_solr_platform_state_pkey'))
    )
    op.create_index(op.f('ix_mw_solr_platform_state_status'), 'mw_solr_platform_state', ['status'], unique=False)
    op.create_index(op.f('ix_mw_solr_platform_state_platform_id'), 'mw_solr_platform_state', ['platform_id'], unique=False)
    op.create_table('mw_ranger_platform',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replica_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpu_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cpu_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('database_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keyadmin_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tagsync_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usersync_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('additional_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('solr_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['mw_pgsql_platform.id'], name=op.f('mw_ranger_platform_database_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name=op.f('mw_ranger_platform_project_id_fkey')),
    sa.ForeignKeyConstraint(['solr_id'], ['mw_solr_platform.id'], name=op.f('mw_ranger_platform_solr_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_ranger_platform_pkey')),
    sa.UniqueConstraint('name', name=op.f('mw_ranger_platform_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mw_ranger_platform_project_id'), 'mw_ranger_platform', ['project_id'], unique=False)
    # ### end Alembic commands ###
