"""remove_chart_version_from_platforms

Revision ID: 30d6d4c5504d
Revises: 30840d7c54af
Create Date: 2026-06-28 23:30:54.152495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '30d6d4c5504d'
down_revision: Union[str, Sequence[str], None] = '30840d7c54af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_airflow_platform', 'chart_version')
    op.drop_column('mw_hive_metastore_platform', 'chart_version')
    op.drop_column('mw_kafka_platform', 'chart_version')
    op.drop_column('mw_nifi_platform', 'chart_version')
    op.drop_column('mw_superset_platform', 'chart_version')
    op.drop_column('mw_trino_platform', 'chart_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('chart_version', sa.VARCHAR(), server_default=sa.text("'1.41.0'::character varying"), autoincrement=False, nullable=False))
    op.add_column('mw_superset_platform', sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_nifi_platform', sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_kafka_platform', sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_hive_metastore_platform', sa.Column('chart_version', sa.VARCHAR(), server_default=sa.text("'latest'::character varying"), autoincrement=False, nullable=False))
    op.add_column('mw_airflow_platform', sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
