"""init

Revision ID: 32d193b1654e
Revises: 3a1ad31ffaa1
Create Date: 2025-11-29 13:03:55.608283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '32d193b1654e'
down_revision: Union[str, Sequence[str], None] = '3a1ad31ffaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_ontology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_ontology_project_id'), 'mw_ontology', ['project_id'], unique=False)
    op.create_table('mw_entity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['mw_ontology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_entity_type_name'), 'mw_entity_type', ['name'], unique=False)
    op.create_table('mw_relationship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['mw_ontology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_relationship_type_name'), 'mw_relationship_type', ['name'], unique=False)
    op.create_table('mw_entity_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['mw_entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_entity_attribute_name'), 'mw_entity_attribute', ['name'], unique=False)
    op.create_table('mw_relationship_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['mw_relationship_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_relationship_attribute_name'), 'mw_relationship_attribute', ['name'], unique=False)
    op.add_column('mw_knowledge_db', sa.Column('ontology_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_knowledge_db', 'mw_ontology', ['ontology_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_knowledge_db', type_='foreignkey')
    op.drop_column('mw_knowledge_db', 'ontology_id')
    op.drop_index(op.f('ix_mw_relationship_attribute_name'), table_name='mw_relationship_attribute')
    op.drop_table('mw_relationship_attribute')
    op.drop_index(op.f('ix_mw_entity_attribute_name'), table_name='mw_entity_attribute')
    op.drop_table('mw_entity_attribute')
    op.drop_index(op.f('ix_mw_relationship_type_name'), table_name='mw_relationship_type')
    op.drop_table('mw_relationship_type')
    op.drop_index(op.f('ix_mw_entity_type_name'), table_name='mw_entity_type')
    op.drop_table('mw_entity_type')
    op.drop_index(op.f('ix_mw_ontology_project_id'), table_name='mw_ontology')
    op.drop_table('mw_ontology')
    # ### end Alembic commands ###
