"""delete

Revision ID: 3496a75f52d4
Revises: 6ae2f807d50c
Create Date: 2026-01-05 15:15:22.419072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3496a75f52d4'
down_revision: Union[str, Sequence[str], None] = '6ae2f807d50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_s3_storage_bucket'), table_name='mw_s3_storage')
    op.drop_column('mw_s3_storage', 'bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_s3_storage', sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_mw_s3_storage_bucket'), 'mw_s3_storage', ['bucket'], unique=False)
    # ### end Alembic commands ###
