"""Add stack service and stack_id to project

Revision ID: 395be299134e
Revises: 9dfab59aa621
Create Date: 2026-06-26 15:37:17.013457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '395be299134e'
down_revision: Union[str, Sequence[str], None] = '9dfab59aa621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('version')
    )
    op.drop_column('mw_airflow_platform', 'image')
    op.drop_column('mw_airflow_platform', 'override_image')
    op.drop_column('mw_hive_metastore_platform', 'image')
    op.drop_column('mw_hive_metastore_platform', 'override_image')
    op.drop_column('mw_kafka_platform', 'image_tag')
    op.drop_column('mw_kafka_platform', 'image')
    op.drop_column('mw_kafka_platform', 'override_image')
    op.drop_column('mw_nifi_platform', 'image_tag')
    op.drop_column('mw_nifi_platform', 'image')
    op.drop_column('mw_nifi_platform', 'override_image')
    op.drop_column('mw_pgsql_platform', 'image')
    op.add_column('mw_project', sa.Column('stack_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_mw_project_stack_id'), 'mw_project', ['stack_id'], unique=False)
    op.create_foreign_key(None, 'mw_project', 'mw_stack', ['stack_id'], ['id'])
    op.drop_column('mw_ranger_platform', 'image')
    op.drop_column('mw_ranger_platform', 'override_image')
    op.drop_column('mw_solr_platform', 'image_tag')
    op.drop_column('mw_solr_platform', 'image')
    op.drop_column('mw_solr_platform', 'override_image')
    op.drop_column('mw_superset_platform', 'image')
    op.drop_column('mw_superset_platform', 'override_image')
    op.drop_column('mw_trino_platform', 'image')
    op.drop_column('mw_trino_platform', 'override_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('override_image', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('mw_trino_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_superset_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_superset_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_solr_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_solr_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_solr_platform', sa.Column('image_tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_ranger_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_ranger_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mw_project', type_='foreignkey')
    op.drop_index(op.f('ix_mw_project_stack_id'), table_name='mw_project')
    op.drop_column('mw_project', 'stack_id')
    op.add_column('mw_pgsql_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_nifi_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_nifi_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_nifi_platform', sa.Column('image_tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_kafka_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_kafka_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_kafka_platform', sa.Column('image_tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_hive_metastore_platform', sa.Column('override_image', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('mw_hive_metastore_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_airflow_platform', sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_airflow_platform', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('mw_stack')
    # ### end Alembic commands ###
