# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add_superset_oidc

Revision ID: 3964797781a2
Revises: 318c38c0b43f
Create Date: 2026-06-04 09:12:40.867976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3964797781a2'
down_revision: Union[str, Sequence[str], None] = '318c38c0b43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_superset_platform', sa.Column('oidc_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE mw_superset_platform SET oidc_enabled = false")
    op.alter_column('mw_superset_platform', 'oidc_enabled', nullable=False)

    op.add_column('mw_superset_platform', sa.Column('oidc_client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE mw_superset_platform SET oidc_client_secret = ''")
    op.alter_column('mw_superset_platform', 'oidc_client_secret', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_superset_platform', 'oidc_client_secret')
    op.drop_column('mw_superset_platform', 'oidc_enabled')
    # ### end Alembic commands ###
