"""init

Revision ID: 3a1ad31ffaa1
Revises: 
Create Date: 2025-11-22 22:11:30.602123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3a1ad31ffaa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mw_ai_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_db_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_ai_agent_project_id'), 'mw_ai_agent', ['project_id'], unique=False)
    op.create_table('mw_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('messages', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_chat_project_id'), 'mw_chat', ['project_id'], unique=False)
    op.create_table('mw_datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_datasource_project_id'), 'mw_datasource', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_datasource_type'), 'mw_datasource', ['type'], unique=False)
    op.create_table('mw_knowledge_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_knowledge_db_project_id'), 'mw_knowledge_db', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_knowledge_db_type'), 'mw_knowledge_db', ['type'], unique=False)
    op.create_table('mw_lakehouse_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_lakehouse_storage_project_id'), 'mw_lakehouse_storage', ['project_id'], unique=False)
    op.create_table('mw_ingestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('lakehouse_storage_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cron_schedule', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ingestion_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['mw_datasource.id'], ),
    sa.ForeignKeyConstraint(['lakehouse_storage_id'], ['mw_lakehouse_storage.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_ingestion_data_source_id'), 'mw_ingestion', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_lakehouse_storage_id'), 'mw_ingestion', ['lakehouse_storage_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_project_id'), 'mw_ingestion', ['project_id'], unique=False)
    op.create_table('mw_ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('watermark_metadata', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['mw_ingestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_ingestion_run_ingestion_id'), 'mw_ingestion_run', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_run_status'), 'mw_ingestion_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_ingestion_run_status'), table_name='mw_ingestion_run')
    op.drop_index(op.f('ix_mw_ingestion_run_ingestion_id'), table_name='mw_ingestion_run')
    op.drop_table('mw_ingestion_run')
    op.drop_index(op.f('ix_mw_ingestion_project_id'), table_name='mw_ingestion')
    op.drop_index(op.f('ix_mw_ingestion_lakehouse_storage_id'), table_name='mw_ingestion')
    op.drop_index(op.f('ix_mw_ingestion_data_source_id'), table_name='mw_ingestion')
    op.drop_table('mw_ingestion')
    op.drop_index(op.f('ix_mw_lakehouse_storage_project_id'), table_name='mw_lakehouse_storage')
    op.drop_table('mw_lakehouse_storage')
    op.drop_index(op.f('ix_mw_knowledge_db_type'), table_name='mw_knowledge_db')
    op.drop_index(op.f('ix_mw_knowledge_db_project_id'), table_name='mw_knowledge_db')
    op.drop_table('mw_knowledge_db')
    op.drop_index(op.f('ix_mw_datasource_type'), table_name='mw_datasource')
    op.drop_index(op.f('ix_mw_datasource_project_id'), table_name='mw_datasource')
    op.drop_table('mw_datasource')
    op.drop_index(op.f('ix_mw_chat_project_id'), table_name='mw_chat')
    op.drop_table('mw_chat')
    op.drop_index(op.f('ix_mw_ai_agent_project_id'), table_name='mw_ai_agent')
    op.drop_table('mw_ai_agent')
    op.drop_table('mw_project')
    # ### end Alembic commands ###
