"""add ranger props

Revision ID: 3a295d96d4ed
Revises: 29624155aa48
Create Date: 2026-04-28 14:49:21.994501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3a295d96d4ed'
down_revision: Union[str, Sequence[str], None] = '29624155aa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ranger_platform', sa.Column('additional_properties', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    op.execute("UPDATE mw_ranger_platform SET additional_properties = '{}'")
    op.alter_column('mw_ranger_platform', 'additional_properties', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_ranger_platform', 'additional_properties')
    # ### end Alembic commands ###
