"""remove_solr_operator_status

Revision ID: 3df6312f2590
Revises: 30d6d4c5504d
Create Date: 2026-06-28 23:39:49.524875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3df6312f2590'
down_revision: Union[str, Sequence[str], None] = '30d6d4c5504d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'solr_operator_installed')
    op.drop_column('mw_k8s_cluster_status', 'solr_operator_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('solr_operator_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mw_k8s_cluster_status', sa.Column('solr_operator_installed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
