# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""remove envoy_gateway_service_type

Revision ID: 3fd6ae8b321a
Revises: 395be299134e
Create Date: 2026-06-26 16:36:58.888363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3fd6ae8b321a'
down_revision: Union[str, Sequence[str], None] = '395be299134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster', 'envoy_gateway_service_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster', sa.Column('envoy_gateway_service_type', sa.VARCHAR(length=12), server_default=sa.text("'NodePort'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
