"""added kafka platform service

Revision ID: 4006a49ba489
Revises: 6b64d26a7c46
Create Date: 2026-06-15 07:09:01.103545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4006a49ba489'
down_revision: Union[str, Sequence[str], None] = '6b64d26a7c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_kafka_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('chart_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override_image', sa.Boolean(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('additional_properties', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_kafka_platform_project_id'), 'mw_kafka_platform', ['project_id'], unique=False)
    op.create_table('mw_kafka_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('kafka_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kafka_url_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_kafka_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_kafka_platform_state_platform_id'), 'mw_kafka_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_kafka_platform_state_status'), 'mw_kafka_platform_state', ['status'], unique=False)
    op.alter_column('mw_solr_platform', 'admin_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_solr_platform', 'admin_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_mw_kafka_platform_state_status'), table_name='mw_kafka_platform_state')
    op.drop_index(op.f('ix_mw_kafka_platform_state_platform_id'), table_name='mw_kafka_platform_state')
    op.drop_table('mw_kafka_platform_state')
    op.drop_index(op.f('ix_mw_kafka_platform_project_id'), table_name='mw_kafka_platform')
    op.drop_table('mw_kafka_platform')
    # ### end Alembic commands ###
