"""refactor k8s cluster

Revision ID: 417aef98e648
Revises: 69cc4df7f157
Create Date: 2026-02-28 08:40:54.033334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '417aef98e648'
down_revision: Union[str, Sequence[str], None] = '69cc4df7f157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_k8s_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('in-cluster', 'remote', name='k8sclustertype', native_enum=False), server_default='remote', nullable=False),
    sa.Column('kubeconfig', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mw_k8s_cluster_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('k8s_cluster_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('nodes_status', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cpu_total', sa.Float(), nullable=False),
    sa.Column('cpu_allocated', sa.Float(), nullable=False),
    sa.Column('ram_total', sa.Float(), nullable=False),
    sa.Column('ram_allocated', sa.Float(), nullable=False),
    sa.Column('argocd_installed', sa.Boolean(), nullable=False),
    sa.Column('argocd_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['k8s_cluster_id'], ['mw_k8s_cluster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('k8s_cluster_id')
    )
    op.drop_table('mw_project_status')
    op.add_column('mw_project', sa.Column('k8s_cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_project', 'mw_k8s_cluster', ['k8s_cluster_id'], ['id'])
    op.drop_column('mw_project', 'k8s_cluster_type')
    op.drop_column('mw_project', 'k8s_cluster_kubeconfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_project', sa.Column('k8s_cluster_kubeconfig', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mw_project', sa.Column('k8s_cluster_type', sa.VARCHAR(length=10), server_default=sa.text("'remote'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mw_project', type_='foreignkey')
    op.drop_column('mw_project', 'k8s_cluster_id')
    op.create_table('mw_project_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('k8s_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('node_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nodes_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cpu_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cpu_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ram_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ram_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('argocd_installed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('argocd_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name=op.f('mw_project_status_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_project_status_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('mw_project_status_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('mw_k8s_cluster_status')
    op.drop_table('mw_k8s_cluster')
    # ### end Alembic commands ###
