"""Add project status tracking

Revision ID: a5af46f57485
Revises: 9248e0ac5f22
Create Date: 2026-02-24 12:17:57.582066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "425c42107165"
down_revision: Union[str, Sequence[str], None] = "9248e0ac5f22"

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mw_project_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("k8s_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column(
            "nodes_status", sqlalchemy_utils.types.json.JSONType(), nullable=False
        ),
        sa.Column("cpu_total", sa.Float(), nullable=False),
        sa.Column("cpu_allocated", sa.Float(), nullable=False),
        sa.Column("ram_total", sa.Float(), nullable=False),
        sa.Column("ram_allocated", sa.Float(), nullable=False),
        sa.Column("argocd_installed", sa.Boolean(), nullable=False),
        sa.Column("argocd_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mw_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mw_project_status")
    # ### end Alembic commands ###
