# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add ranger_id to trino

Revision ID: 45e95b334192
Revises: 035cec8b1ae3
Create Date: 2026-05-24 08:51:21.019830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '45e95b334192'
down_revision: Union[str, Sequence[str], None] = '035cec8b1ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('ranger_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_trino_platform', 'mw_ranger_platform', ['ranger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_trino_platform', type_='foreignkey')
    op.drop_column('mw_trino_platform', 'ranger_id')
    # ### end Alembic commands ###
