"""Initial MVP release

Revision ID: 4bdd79855a91
Revises: 
Create Date: 2026-06-29 06:16:49.890938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4bdd79855a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_k8s_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('in-cluster', 'remote', name='k8sclustertype', native_enum=False), server_default='remote', nullable=False),
    sa.Column('kubeconfig', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mw_ldap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bind_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bind_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_search_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_search_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_search_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_search_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_member_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_group_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mw_name_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_name_tracker_name'), 'mw_name_tracker', ['name'], unique=True)
    op.create_table('mw_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('version')
    )
    op.create_table('mw_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_user_email'), 'mw_user', ['email'], unique=True)
    op.create_index(op.f('ix_mw_user_name'), 'mw_user', ['name'], unique=True)
    op.create_table('mw_k8s_cluster_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('k8s_cluster_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('nodes_status', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('node_ips', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cpu_total', sa.Float(), nullable=False),
    sa.Column('cpu_allocated', sa.Float(), nullable=False),
    sa.Column('ram_total', sa.Float(), nullable=False),
    sa.Column('ram_allocated', sa.Float(), nullable=False),
    sa.Column('argocd_installed', sa.Boolean(), nullable=False),
    sa.Column('argocd_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cert_manager_installed', sa.Boolean(), nullable=False),
    sa.Column('cert_manager_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cnpg_installed', sa.Boolean(), nullable=False),
    sa.Column('cnpg_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_issuer_installed', sa.Boolean(), nullable=False),
    sa.Column('envoy_gateway_installed', sa.Boolean(), nullable=False),
    sa.Column('envoy_gateway_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kafka_operator_installed', sa.Boolean(), nullable=False),
    sa.Column('kafka_operator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nifikop_installed', sa.Boolean(), nullable=False),
    sa.Column('nifikop_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['k8s_cluster_id'], ['mw_k8s_cluster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('k8s_cluster_id')
    )
    op.create_table('mw_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_namespace', sa.String(length=32), nullable=True),
    sa.Column('k8s_cluster_id', sa.Integer(), nullable=False),
    sa.Column('ldap_config_id', sa.Integer(), nullable=True),
    sa.Column('ingress_domain', sa.String(length=255), nullable=True),
    sa.Column('envoy_gateway_service_type', sa.Enum('LoadBalancer', 'NodePort', name='envoygatewayservicetype', native_enum=False), server_default='LoadBalancer', nullable=False),
    sa.Column('envoy_nodeport', sa.Integer(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['k8s_cluster_id'], ['mw_k8s_cluster.id'], ),
    sa.ForeignKeyConstraint(['ldap_config_id'], ['mw_ldap_config.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['mw_stack.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_project_stack_id'), 'mw_project', ['stack_id'], unique=False)
    op.create_table('mw_container_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_container_registry_project_id'), 'mw_container_registry', ['project_id'], unique=False)
    op.create_table('mw_database_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=255), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_database_source_project_id'), 'mw_database_source', ['project_id'], unique=False)
    op.create_table('mw_kafka_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('additional_properties', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_kafka_platform_project_id'), 'mw_kafka_platform', ['project_id'], unique=False)
    op.create_table('mw_nifi_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('additional_properties', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_nifi_platform_project_id'), 'mw_nifi_platform', ['project_id'], unique=False)
    op.create_table('mw_project_local_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash_bcrypt', sa.String(length=255), nullable=True),
    sa.Column('password_hash_md5', sa.String(length=255), nullable=True),
    sa.Column('password_hash_sha256', sa.String(length=255), nullable=True),
    sa.Column('password_hash_sha512', sa.String(length=255), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_project_local_user_email'), 'mw_project_local_user', ['email'], unique=True)
    op.create_index(op.f('ix_mw_project_local_user_project_id'), 'mw_project_local_user', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_project_local_user_username'), 'mw_project_local_user', ['username'], unique=True)
    op.create_table('mw_s3_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_s3_storage_project_id'), 'mw_s3_storage', ['project_id'], unique=False)
    op.create_table('mw_ssh_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ssh_key_project_id'), 'mw_ssh_key', ['project_id'], unique=False)
    op.create_table('mw_trino_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('hms_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('database_source_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('process_forwarded', sa.Boolean(), nullable=False),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_shared_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_trino_platform_project_id'), 'mw_trino_platform', ['project_id'], unique=False)
    op.create_table('mw_git_repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ssh_key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['mw_ssh_key.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_git_repo_project_id'), 'mw_git_repo', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_git_repo_ssh_key_id'), 'mw_git_repo', ['ssh_key_id'], unique=False)
    op.create_table('mw_kafka_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('kafka_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kafka_url_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_kafka_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_kafka_platform_state_platform_id'), 'mw_kafka_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_kafka_platform_state_status'), 'mw_kafka_platform_state', ['status'], unique=False)
    op.create_table('mw_nifi_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('nifi_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_nifi_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_nifi_platform_state_platform_id'), 'mw_nifi_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_nifi_platform_state_status'), 'mw_nifi_platform_state', ['status'], unique=False)
    op.create_table('mw_pgsql_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('instances', sa.Integer(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('enable_backup', sa.Boolean(), nullable=False),
    sa.Column('backup_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_retention_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=True),
    sa.Column('pgbouncer_pool_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pgbouncer_pool_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_project_id'), 'mw_pgsql_platform', ['project_id'], unique=False)
    op.create_table('mw_trino_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('trino_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_trino_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_trino_platform_state_platform_id'), 'mw_trino_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_trino_platform_state_status'), 'mw_trino_platform_state', ['status'], unique=False)
    op.create_table('mw_airflow_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('redis_enabled', sa.Boolean(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=True),
    sa.Column('logs_s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fernet_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webserver_secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oidc_enabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_pgsql_id', sa.Integer(), nullable=False),
    sa.Column('auth_role_mapping', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('dags_git_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('git_repo_id', sa.Integer(), nullable=True),
    sa.Column('dags_git_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dags_git_subpath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['git_repo_id'], ['mw_git_repo.id'], ),
    sa.ForeignKeyConstraint(['platform_pgsql_id'], ['mw_pgsql_platform.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_airflow_platform_project_id'), 'mw_airflow_platform', ['project_id'], unique=False)
    op.create_table('mw_hive_metastore_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=True),
    sa.Column('iceberg_enabled', sa.Boolean(), nullable=False),
    sa.Column('warehouse_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['mw_pgsql_platform.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_hive_metastore_platform_project_id'), 'mw_hive_metastore_platform', ['project_id'], unique=False)
    op.create_table('mw_pgsql_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('db_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_ca_crt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_pgsql_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_state_platform_id'), 'mw_pgsql_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_pgsql_platform_state_status'), 'mw_pgsql_platform_state', ['status'], unique=False)
    op.create_table('mw_superset_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('superset_secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oidc_enabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sqllab_enabled', sa.Boolean(), nullable=False),
    sa.Column('platform_pgsql_id', sa.Integer(), nullable=False),
    sa.Column('database_source_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('trino_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('auth_role_mapping', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['platform_pgsql_id'], ['mw_pgsql_platform.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_superset_platform_project_id'), 'mw_superset_platform', ['project_id'], unique=False)
    op.create_table('mw_airflow_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('airflow_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('airflow_uri_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_airflow_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_airflow_platform_state_platform_id'), 'mw_airflow_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_airflow_platform_state_status'), 'mw_airflow_platform_state', ['status'], unique=False)
    op.create_table('mw_hive_metastore_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('hms_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iceberg_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_hive_metastore_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_hive_metastore_platform_state_platform_id'), 'mw_hive_metastore_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_hive_metastore_platform_state_status'), 'mw_hive_metastore_platform_state', ['status'], unique=False)
    op.create_table('mw_superset_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('superset_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superset_uri_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_superset_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_superset_platform_state_platform_id'), 'mw_superset_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_superset_platform_state_status'), 'mw_superset_platform_state', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_superset_platform_state_status'), table_name='mw_superset_platform_state')
    op.drop_index(op.f('ix_mw_superset_platform_state_platform_id'), table_name='mw_superset_platform_state')
    op.drop_table('mw_superset_platform_state')
    op.drop_index(op.f('ix_mw_hive_metastore_platform_state_status'), table_name='mw_hive_metastore_platform_state')
    op.drop_index(op.f('ix_mw_hive_metastore_platform_state_platform_id'), table_name='mw_hive_metastore_platform_state')
    op.drop_table('mw_hive_metastore_platform_state')
    op.drop_index(op.f('ix_mw_airflow_platform_state_status'), table_name='mw_airflow_platform_state')
    op.drop_index(op.f('ix_mw_airflow_platform_state_platform_id'), table_name='mw_airflow_platform_state')
    op.drop_table('mw_airflow_platform_state')
    op.drop_index(op.f('ix_mw_superset_platform_project_id'), table_name='mw_superset_platform')
    op.drop_table('mw_superset_platform')
    op.drop_index(op.f('ix_mw_pgsql_platform_state_status'), table_name='mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_pgsql_platform_state_platform_id'), table_name='mw_pgsql_platform_state')
    op.drop_table('mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_hive_metastore_platform_project_id'), table_name='mw_hive_metastore_platform')
    op.drop_table('mw_hive_metastore_platform')
    op.drop_index(op.f('ix_mw_airflow_platform_project_id'), table_name='mw_airflow_platform')
    op.drop_table('mw_airflow_platform')
    op.drop_index(op.f('ix_mw_trino_platform_state_status'), table_name='mw_trino_platform_state')
    op.drop_index(op.f('ix_mw_trino_platform_state_platform_id'), table_name='mw_trino_platform_state')
    op.drop_table('mw_trino_platform_state')
    op.drop_index(op.f('ix_mw_pgsql_platform_project_id'), table_name='mw_pgsql_platform')
    op.drop_table('mw_pgsql_platform')
    op.drop_index(op.f('ix_mw_nifi_platform_state_status'), table_name='mw_nifi_platform_state')
    op.drop_index(op.f('ix_mw_nifi_platform_state_platform_id'), table_name='mw_nifi_platform_state')
    op.drop_table('mw_nifi_platform_state')
    op.drop_index(op.f('ix_mw_kafka_platform_state_status'), table_name='mw_kafka_platform_state')
    op.drop_index(op.f('ix_mw_kafka_platform_state_platform_id'), table_name='mw_kafka_platform_state')
    op.drop_table('mw_kafka_platform_state')
    op.drop_index(op.f('ix_mw_git_repo_ssh_key_id'), table_name='mw_git_repo')
    op.drop_index(op.f('ix_mw_git_repo_project_id'), table_name='mw_git_repo')
    op.drop_table('mw_git_repo')
    op.drop_index(op.f('ix_mw_trino_platform_project_id'), table_name='mw_trino_platform')
    op.drop_table('mw_trino_platform')
    op.drop_index(op.f('ix_mw_ssh_key_project_id'), table_name='mw_ssh_key')
    op.drop_table('mw_ssh_key')
    op.drop_index(op.f('ix_mw_s3_storage_project_id'), table_name='mw_s3_storage')
    op.drop_table('mw_s3_storage')
    op.drop_index(op.f('ix_mw_project_local_user_username'), table_name='mw_project_local_user')
    op.drop_index(op.f('ix_mw_project_local_user_project_id'), table_name='mw_project_local_user')
    op.drop_index(op.f('ix_mw_project_local_user_email'), table_name='mw_project_local_user')
    op.drop_table('mw_project_local_user')
    op.drop_index(op.f('ix_mw_nifi_platform_project_id'), table_name='mw_nifi_platform')
    op.drop_table('mw_nifi_platform')
    op.drop_index(op.f('ix_mw_kafka_platform_project_id'), table_name='mw_kafka_platform')
    op.drop_table('mw_kafka_platform')
    op.drop_index(op.f('ix_mw_database_source_project_id'), table_name='mw_database_source')
    op.drop_table('mw_database_source')
    op.drop_index(op.f('ix_mw_container_registry_project_id'), table_name='mw_container_registry')
    op.drop_table('mw_container_registry')
    op.drop_index(op.f('ix_mw_project_stack_id'), table_name='mw_project')
    op.drop_table('mw_project')
    op.drop_table('mw_k8s_cluster_status')
    op.drop_index(op.f('ix_mw_user_name'), table_name='mw_user')
    op.drop_index(op.f('ix_mw_user_email'), table_name='mw_user')
    op.drop_table('mw_user')
    op.drop_table('mw_stack')
    op.drop_index(op.f('ix_mw_name_tracker_name'), table_name='mw_name_tracker')
    op.drop_table('mw_name_tracker')
    op.drop_table('mw_ldap_config')
    op.drop_table('mw_k8s_cluster')
    # ### end Alembic commands ###
