# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add_ranger_to_nifi

Revision ID: 538936604bd3
Revises: 9dfab59aa621
Create Date: 2026-06-25 20:42:23.793562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '538936604bd3'
down_revision: Union[str, Sequence[str], None] = '9dfab59aa621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_nifi_platform', sa.Column('ranger_id', sa.Integer(), nullable=True))
    op.add_column('mw_nifi_platform', sa.Column('ranger_user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'mw_nifi_platform', 'mw_ranger_platform', ['ranger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_nifi_platform', type_='foreignkey')
    op.drop_column('mw_nifi_platform', 'ranger_user_password')
    op.drop_column('mw_nifi_platform', 'ranger_id')
    # ### end Alembic commands ###
