"""remove_dex_from_cluster_status

Revision ID: 53c979f5673b
Revises: d8840e9c00cd
Create Date: 2026-05-30 07:44:07.679191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '53c979f5673b'
down_revision: Union[str, Sequence[str], None] = 'd8840e9c00cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'dex_installed')
    op.drop_column('mw_k8s_cluster_status', 'dex_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('dex_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mw_k8s_cluster_status', sa.Column('dex_installed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
