# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""link airflow to git repo service

Revision ID: 56051589a7ce
Revises: 9601bf89428e
Create Date: 2026-06-11 15:12:48.994475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '56051589a7ce'
down_revision: Union[str, Sequence[str], None] = '9601bf89428e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('git_repo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_airflow_platform', 'mw_git_repo', ['git_repo_id'], ['id'])
    op.drop_column('mw_airflow_platform', 'dags_git_repo')
    op.drop_column('mw_airflow_platform', 'dags_git_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('dags_git_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mw_airflow_platform', sa.Column('dags_git_repo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mw_airflow_platform', type_='foreignkey')
    op.drop_column('mw_airflow_platform', 'git_repo_id')
    # ### end Alembic commands ###
