"""added s3 to hms

Revision ID: 56e6735ed20e
Revises: bbaba09ce176
Create Date: 2026-03-14 11:09:18.603707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '56e6735ed20e'
down_revision: Union[str, Sequence[str], None] = 'bbaba09ce176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_hive_metastore_platform', sa.Column('s3_storage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_hive_metastore_platform', 'mw_s3_storage', ['s3_storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_hive_metastore_platform', type_='foreignkey')
    op.drop_column('mw_hive_metastore_platform', 's3_storage_id')
    # ### end Alembic commands ###
