"""add ranger state passwords

Revision ID: 5a4c6491c5ba
Revises: 3a295d96d4ed
Create Date: 2026-04-28 14:59:55.222906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a4c6491c5ba'
down_revision: Union[str, Sequence[str], None] = '3a295d96d4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ranger_platform_state', sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_ranger_platform_state', sa.Column('keyadmin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_ranger_platform_state', sa.Column('tagsync_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_ranger_platform_state', sa.Column('usersync_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_ranger_platform_state', 'usersync_password')
    op.drop_column('mw_ranger_platform_state', 'tagsync_password')
    op.drop_column('mw_ranger_platform_state', 'keyadmin_password')
    op.drop_column('mw_ranger_platform_state', 'admin_password')
    # ### end Alembic commands ###
