"""add nifi platform

Revision ID: 6064e87e6331
Revises: f81c1d1a3974
Create Date: 2026-06-18 16:23:54.865416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6064e87e6331'
down_revision: Union[str, Sequence[str], None] = 'f81c1d1a3974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_nifi_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('replica_count', sa.Integer(), nullable=False),
    sa.Column('chart_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override_image', sa.Boolean(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('additional_properties', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_nifi_platform_project_id'), 'mw_nifi_platform', ['project_id'], unique=False)
    op.create_table('mw_nifi_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('nifi_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_nifi_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_nifi_platform_state_platform_id'), 'mw_nifi_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_nifi_platform_state_status'), 'mw_nifi_platform_state', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_nifi_platform_state_status'), table_name='mw_nifi_platform_state')
    op.drop_index(op.f('ix_mw_nifi_platform_state_platform_id'), table_name='mw_nifi_platform_state')
    op.drop_table('mw_nifi_platform_state')
    op.drop_index(op.f('ix_mw_nifi_platform_project_id'), table_name='mw_nifi_platform')
    op.drop_table('mw_nifi_platform')
    # ### end Alembic commands ###
