"""initialize

Revision ID: 69cc4df7f157
Revises: 
Create Date: 2026-02-27 05:04:42.508529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '69cc4df7f157'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_namespace', sa.String(length=32), nullable=True),
    sa.Column('k8s_cluster_type', sa.Enum('in-cluster', 'remote', name='k8sclustertype', native_enum=False), server_default='remote', nullable=False),
    sa.Column('k8s_cluster_kubeconfig', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mw_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_user_email'), 'mw_user', ['email'], unique=True)
    op.create_index(op.f('ix_mw_user_name'), 'mw_user', ['name'], unique=True)
    op.create_table('mw_datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=500), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_datasource_project_id'), 'mw_datasource', ['project_id'], unique=False)
    op.create_table('mw_project_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('nodes_status', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cpu_total', sa.Float(), nullable=False),
    sa.Column('cpu_allocated', sa.Float(), nullable=False),
    sa.Column('ram_total', sa.Float(), nullable=False),
    sa.Column('ram_allocated', sa.Float(), nullable=False),
    sa.Column('argocd_installed', sa.Boolean(), nullable=False),
    sa.Column('argocd_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('mw_s3_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_s3_storage_project_id'), 'mw_s3_storage', ['project_id'], unique=False)
    op.create_table('mw_pgsql_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('instances', sa.Integer(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('enable_backup', sa.Boolean(), nullable=False),
    sa.Column('backup_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_retention_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_project_id'), 'mw_pgsql_platform', ['project_id'], unique=False)
    op.create_table('mw_pgsql_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('db_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_ca_crt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_pgsql_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_state_platform_id'), 'mw_pgsql_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_pgsql_platform_state_status'), 'mw_pgsql_platform_state', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_pgsql_platform_state_status'), table_name='mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_pgsql_platform_state_platform_id'), table_name='mw_pgsql_platform_state')
    op.drop_table('mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_pgsql_platform_project_id'), table_name='mw_pgsql_platform')
    op.drop_table('mw_pgsql_platform')
    op.drop_index(op.f('ix_mw_s3_storage_project_id'), table_name='mw_s3_storage')
    op.drop_table('mw_s3_storage')
    op.drop_table('mw_project_status')
    op.drop_index(op.f('ix_mw_datasource_project_id'), table_name='mw_datasource')
    op.drop_table('mw_datasource')
    op.drop_index(op.f('ix_mw_user_name'), table_name='mw_user')
    op.drop_index(op.f('ix_mw_user_email'), table_name='mw_user')
    op.drop_table('mw_user')
    op.drop_table('mw_project')
    # ### end Alembic commands ###
