"""Add User table

Revision ID: 6ae2f807d50c
Revises: 0628a1b798f1
Create Date: 2026-01-05 01:32:35.568953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6ae2f807d50c'
down_revision: Union[str, Sequence[str], None] = '0628a1b798f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_pgsql_platform', sa.Column('enable_backup', sa.Boolean(), nullable=True))
    op.execute("UPDATE mw_pgsql_platform SET enable_backup = False")
    op.alter_column('mw_pgsql_platform', 'enable_backup', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_pgsql_platform', 'enable_backup')
    # ### end Alembic commands ###
