"""airflow: only celery executor, add redis

Revision ID: 6f04b916c872
Revises: d59af43967e1
Create Date: 2026-06-10 07:13:10.932667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6f04b916c872'
down_revision: Union[str, Sequence[str], None] = 'd59af43967e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('redis_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.drop_column('mw_airflow_platform', 'executor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('executor', sa.VARCHAR(), autoincrement=False, nullable=False, server_default='CeleryExecutor'))
    op.drop_column('mw_airflow_platform', 'redis_enabled')
    # ### end Alembic commands ###
