"""add solr_internal_url to solr platform state

Revision ID: 8685321b5a3e
Revises: b2d057080e09
Create Date: 2026-06-08 16:54:21.835669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8685321b5a3e'
down_revision: Union[str, Sequence[str], None] = 'b2d057080e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_solr_platform_state', sa.Column('solr_internal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_solr_platform_state', 'solr_internal_url')
    # ### end Alembic commands ###
