"""add cert-manager and cnpg operator tracker

Revision ID: 872f647e1af6
Revises: 653c40a290ee
Create Date: 2026-03-15 10:17:49.315443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '872f647e1af6'
down_revision: Union[str, Sequence[str], None] = '653c40a290ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('cert_manager_installed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('cert_manager_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_k8s_cluster_status', sa.Column('cnpg_installed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('cnpg_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'cnpg_version')
    op.drop_column('mw_k8s_cluster_status', 'cnpg_installed')
    op.drop_column('mw_k8s_cluster_status', 'cert_manager_version')
    op.drop_column('mw_k8s_cluster_status', 'cert_manager_installed')
    # ### end Alembic commands ###
