"""add backup schedule

Revision ID: 9248e0ac5f22
Revises: df775e492f08
Create Date: 2026-02-24 11:58:56.442004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9248e0ac5f22'
down_revision: Union[str, Sequence[str], None] = 'df775e492f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_pgsql_platform', sa.Column('backup_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_pgsql_platform', 'backup_schedule')
    # ### end Alembic commands ###
