# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add load_examples to airflow and superset

Revision ID: 92b6d8b76342
Revises: 4bdd79855a91
Create Date: 2026-07-05 19:08:12.747539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '92b6d8b76342'
down_revision: Union[str, Sequence[str], None] = '4bdd79855a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('load_examples', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_superset_platform', sa.Column('load_examples', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_superset_platform', 'load_examples')
    op.drop_column('mw_airflow_platform', 'load_examples')
    # ### end Alembic commands ###
