"""remove auth type from git repo table

Revision ID: 9601bf89428e
Revises: b86fac7dab12
Create Date: 2026-06-11 14:22:42.414801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9601bf89428e'
down_revision: Union[str, Sequence[str], None] = 'b86fac7dab12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_git_repo', 'auth_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_git_repo', sa.Column('auth_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
