"""add dictionary fields to datasources

Revision ID: 997ede4dadde
Revises: 285e72a8f941
Create Date: 2026-03-17 07:07:52.473890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '997ede4dadde'
down_revision: Union[str, Sequence[str], None] = '285e72a8f941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_api_source', sa.Column('headers', sqlalchemy_utils.types.json.JSONType(), nullable=False))
    op.add_column('mw_streaming_source', sa.Column('extra_config', sqlalchemy_utils.types.json.JSONType(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_streaming_source', 'extra_config')
    op.drop_column('mw_api_source', 'headers')
    # ### end Alembic commands ###
