"""remove_zookeeper

Revision ID: 9c663be33267
Revises: 7be089973d0c
Create Date: 2026-06-16 11:23:57.619795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c663be33267'
down_revision: Union[str, Sequence[str], None] = '7be089973d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_zookeeper_platform_state_platform_id'), table_name='mw_zookeeper_platform_state')
    op.drop_index(op.f('ix_mw_zookeeper_platform_state_status'), table_name='mw_zookeeper_platform_state')
    op.drop_table('mw_zookeeper_platform_state')
    op.drop_index(op.f('ix_mw_zookeeper_platform_project_id'), table_name='mw_zookeeper_platform')
    op.drop_constraint(op.f('mw_solr_platform_zookeeper_id_fkey'), 'mw_solr_platform', type_='foreignkey')
    op.drop_column('mw_solr_platform', 'zookeeper_id')
    op.drop_table('mw_zookeeper_platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_solr_platform', sa.Column('zookeeper_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mw_solr_platform_zookeeper_id_fkey'), 'mw_solr_platform', 'mw_zookeeper_platform', ['zookeeper_id'], ['id'])
    op.create_table('mw_zookeeper_platform',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mw_zookeeper_platform_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replica_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chart_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('override_image', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpu_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cpu_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_request', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mem_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('additional_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name='mw_zookeeper_platform_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mw_zookeeper_platform_pkey'),
    sa.UniqueConstraint('name', name='mw_zookeeper_platform_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_mw_zookeeper_platform_project_id'), 'mw_zookeeper_platform', ['project_id'], unique=False)
    op.create_table('mw_zookeeper_platform_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('node_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cluster_nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('zookeeper_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zookeeper_url_ipv6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_zookeeper_platform.id'], name=op.f('mw_zookeeper_platform_state_platform_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_zookeeper_platform_state_pkey'))
    )
    op.create_index(op.f('ix_mw_zookeeper_platform_state_status'), 'mw_zookeeper_platform_state', ['status'], unique=False)
    op.create_index(op.f('ix_mw_zookeeper_platform_state_platform_id'), 'mw_zookeeper_platform_state', ['platform_id'], unique=False)
    # ### end Alembic commands ###
