# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""initial

Revision ID: a1fd5c41265e
Revises: 
Create Date: 2026-02-21 14:29:22.071407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a1fd5c41265e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8s_namespace', sa.String(length=32), nullable=True),
    sa.Column('k8s_cluster_type', sa.Enum('in-cluster', 'remote', name='k8sclustertype', native_enum=False), server_default='remote', nullable=False),
    sa.Column('k8s_cluster_kubeconfig', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mw_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_user_email'), 'mw_user', ['email'], unique=True)
    op.create_table('mw_ai_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_db_ids', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ai_agent_project_id'), 'mw_ai_agent', ['project_id'], unique=False)
    op.create_table('mw_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('messages', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_chat_project_id'), 'mw_chat', ['project_id'], unique=False)
    op.create_table('mw_datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=500), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_datasource_project_id'), 'mw_datasource', ['project_id'], unique=False)
    op.create_table('mw_ontology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ontology_project_id'), 'mw_ontology', ['project_id'], unique=False)
    op.create_table('mw_s3_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_s3_storage_project_id'), 'mw_s3_storage', ['project_id'], unique=False)
    op.create_table('mw_entity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['mw_ontology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_entity_type_name'), 'mw_entity_type', ['name'], unique=False)
    op.create_table('mw_ingestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cron_schedule', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ingestion_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['mw_datasource.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ingestion_data_source_id'), 'mw_ingestion', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_project_id'), 'mw_ingestion', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_s3_storage_id'), 'mw_ingestion', ['s3_storage_id'], unique=False)
    op.create_table('mw_knowledge_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['mw_ontology.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_knowledge_db_project_id'), 'mw_knowledge_db', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_knowledge_db_type'), 'mw_knowledge_db', ['type'], unique=False)
    op.create_table('mw_pgsql_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('instances', sa.Integer(), nullable=False),
    sa.Column('storage_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.Column('enable_backup', sa.Boolean(), nullable=False),
    sa.Column('backup_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_retention_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_storage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['s3_storage_id'], ['mw_s3_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_project_id'), 'mw_pgsql_platform', ['project_id'], unique=False)
    op.create_table('mw_relationship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['mw_ontology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_relationship_type_name'), 'mw_relationship_type', ['name'], unique=False)
    op.create_table('mw_entity_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['mw_entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_entity_attribute_name'), 'mw_entity_attribute', ['name'], unique=False)
    op.create_table('mw_ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('watermark_metadata', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['mw_ingestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_ingestion_run_ingestion_id'), 'mw_ingestion_run', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_mw_ingestion_run_status'), 'mw_ingestion_run', ['status'], unique=False)
    op.create_table('mw_pgsql_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('db_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_ca_crt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_pgsql_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_pgsql_platform_state_platform_id'), 'mw_pgsql_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_pgsql_platform_state_status'), 'mw_pgsql_platform_state', ['status'], unique=False)
    op.create_table('mw_relationship_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['mw_relationship_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_relationship_attribute_name'), 'mw_relationship_attribute', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_relationship_attribute_name'), table_name='mw_relationship_attribute')
    op.drop_table('mw_relationship_attribute')
    op.drop_index(op.f('ix_mw_pgsql_platform_state_status'), table_name='mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_pgsql_platform_state_platform_id'), table_name='mw_pgsql_platform_state')
    op.drop_table('mw_pgsql_platform_state')
    op.drop_index(op.f('ix_mw_ingestion_run_status'), table_name='mw_ingestion_run')
    op.drop_index(op.f('ix_mw_ingestion_run_ingestion_id'), table_name='mw_ingestion_run')
    op.drop_table('mw_ingestion_run')
    op.drop_index(op.f('ix_mw_entity_attribute_name'), table_name='mw_entity_attribute')
    op.drop_table('mw_entity_attribute')
    op.drop_index(op.f('ix_mw_relationship_type_name'), table_name='mw_relationship_type')
    op.drop_table('mw_relationship_type')
    op.drop_index(op.f('ix_mw_pgsql_platform_project_id'), table_name='mw_pgsql_platform')
    op.drop_table('mw_pgsql_platform')
    op.drop_index(op.f('ix_mw_knowledge_db_type'), table_name='mw_knowledge_db')
    op.drop_index(op.f('ix_mw_knowledge_db_project_id'), table_name='mw_knowledge_db')
    op.drop_table('mw_knowledge_db')
    op.drop_index(op.f('ix_mw_ingestion_s3_storage_id'), table_name='mw_ingestion')
    op.drop_index(op.f('ix_mw_ingestion_project_id'), table_name='mw_ingestion')
    op.drop_index(op.f('ix_mw_ingestion_data_source_id'), table_name='mw_ingestion')
    op.drop_table('mw_ingestion')
    op.drop_index(op.f('ix_mw_entity_type_name'), table_name='mw_entity_type')
    op.drop_table('mw_entity_type')
    op.drop_index(op.f('ix_mw_s3_storage_project_id'), table_name='mw_s3_storage')
    op.drop_table('mw_s3_storage')
    op.drop_index(op.f('ix_mw_ontology_project_id'), table_name='mw_ontology')
    op.drop_table('mw_ontology')
    op.drop_index(op.f('ix_mw_datasource_project_id'), table_name='mw_datasource')
    op.drop_table('mw_datasource')
    op.drop_index(op.f('ix_mw_chat_project_id'), table_name='mw_chat')
    op.drop_table('mw_chat')
    op.drop_index(op.f('ix_mw_ai_agent_project_id'), table_name='mw_ai_agent')
    op.drop_table('mw_ai_agent')
    op.drop_index(op.f('ix_mw_user_email'), table_name='mw_user')
    op.drop_table('mw_user')
    op.drop_table('mw_project')
    # ### end Alembic commands ###
