"""remove keda

Revision ID: a6d4435f371a
Revises: dc3748cbcd22
Create Date: 2026-03-14 14:41:21.934192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a6d4435f371a'
down_revision: Union[str, Sequence[str], None] = 'dc3748cbcd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_trino_platform', 'keda_min_replicas')
    op.drop_column('mw_trino_platform', 'keda_max_replicas')
    op.drop_column('mw_trino_platform', 'keda_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('keda_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mw_trino_platform', sa.Column('keda_max_replicas', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mw_trino_platform', sa.Column('keda_min_replicas', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
