# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""remove s3 logging from ranger

Revision ID: ad7ac4016dfb
Revises: 1bf3aa25102c
Create Date: 2026-05-26 15:27:51.808604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ad7ac4016dfb'
down_revision: Union[str, Sequence[str], None] = '1bf3aa25102c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mw_ranger_platform_s3_storage_id_fkey'), 'mw_ranger_platform', type_='foreignkey')
    op.drop_column('mw_ranger_platform', 's3_storage_id')
    op.drop_column('mw_ranger_platform', 'audit_s3_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ranger_platform', sa.Column('audit_s3_uri', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mw_ranger_platform', sa.Column('s3_storage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mw_ranger_platform_s3_storage_id_fkey'), 'mw_ranger_platform', 'mw_s3_storage', ['s3_storage_id'], ['id'])
    # ### end Alembic commands ###
