"""add algorithm and key size to ssh key table

Revision ID: b86fac7dab12
Revises: e48885dbe83c
Create Date: 2026-06-11 14:18:15.118535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b86fac7dab12'
down_revision: Union[str, Sequence[str], None] = 'e48885dbe83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ssh_key', sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='rsa'))
    op.add_column('mw_ssh_key', sa.Column('key_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_ssh_key', 'key_size')
    op.drop_column('mw_ssh_key', 'algorithm')
    # ### end Alembic commands ###
