"""airflow add s3 storage for log store

Revision ID: ba9fb2def85d
Revises: 6f04b916c872
Create Date: 2026-06-10 11:14:57.562698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ba9fb2def85d'
down_revision: Union[str, Sequence[str], None] = '6f04b916c872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('s3_storage_id', sa.Integer(), nullable=True))
    op.add_column('mw_airflow_platform', sa.Column('logs_s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.create_foreign_key(None, 'mw_airflow_platform', 'mw_s3_storage', ['s3_storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_airflow_platform', type_='foreignkey')
    op.drop_column('mw_airflow_platform', 'logs_s3_bucket')
    op.drop_column('mw_airflow_platform', 's3_storage_id')
    # ### end Alembic commands ###
