"""remove pictures field from user

Revision ID: bedf64fc5404
Revises: e8b19a823c14
Create Date: 2026-09-22 08:43:33.288406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bedf64fc5404'
down_revision: Union[str, Sequence[str], None] = 'e8b19a823c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_user', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_user', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
