"""added_audit_s3_uri_to_ranger

Revision ID: c49e460adb24
Revises: 20c4d8bacdc0
Create Date: 2026-04-05 19:38:18.451755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c49e460adb24'
down_revision: Union[str, Sequence[str], None] = '20c4d8bacdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_ranger_platform', sa.Column('audit_s3_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_ranger_platform', 'audit_s3_uri')
    # ### end Alembic commands ###
