# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add solr operator status fields

Revision ID: d092604db5a9
Revises: 347f102d3d1f
Create Date: 2026-06-07 09:45:46.143331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd092604db5a9'
down_revision: Union[str, Sequence[str], None] = '347f102d3d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('solr_operator_installed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('solr_operator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'solr_operator_version')
    op.drop_column('mw_k8s_cluster_status', 'solr_operator_installed')
    # ### end Alembic commands ###
