"""added airflow platform service

Revision ID: d59af43967e1
Revises: e69a93249137
Create Date: 2026-06-10 07:08:26.124105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd59af43967e1'
down_revision: Union[str, Sequence[str], None] = 'e69a93249137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_airflow_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chart_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override_image', sa.Boolean(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fernet_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webserver_secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oidc_enabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_pgsql_id', sa.Integer(), nullable=False),
    sa.Column('auth_role_mapping', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('dags_git_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('dags_git_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dags_git_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dags_git_subpath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dags_git_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpu_request', sa.Float(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('mem_request', sa.Float(), nullable=False),
    sa.Column('mem_limit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['platform_pgsql_id'], ['mw_pgsql_platform.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_airflow_platform_project_id'), 'mw_airflow_platform', ['project_id'], unique=False)
    op.create_table('mw_airflow_platform_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_ports', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('cluster_nodes', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('extra_data', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('airflow_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('airflow_uri_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['mw_airflow_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_airflow_platform_state_platform_id'), 'mw_airflow_platform_state', ['platform_id'], unique=False)
    op.create_index(op.f('ix_mw_airflow_platform_state_status'), 'mw_airflow_platform_state', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_airflow_platform_state_status'), table_name='mw_airflow_platform_state')
    op.drop_index(op.f('ix_mw_airflow_platform_state_platform_id'), table_name='mw_airflow_platform_state')
    op.drop_table('mw_airflow_platform_state')
    op.drop_index(op.f('ix_mw_airflow_platform_project_id'), table_name='mw_airflow_platform')
    op.drop_table('mw_airflow_platform')
    # ### end Alembic commands ###
