# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""added_ipv6_to_ranger_and_opensearch

Revision ID: d763700c5c90
Revises: a828e213a7fe
Create Date: 2026-05-22 19:48:11.446682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd763700c5c90'
down_revision: Union[str, Sequence[str], None] = 'a828e213a7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_opensearch_platform_state', sa.Column('opensearch_url_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_ranger_platform_state', sa.Column('ranger_url_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_ranger_platform_state', 'ranger_url_ipv6')
    op.drop_column('mw_opensearch_platform_state', 'opensearch_url_ipv6')
    # ### end Alembic commands ###
