"""add_dex_and_project_local_users

Revision ID: d8840e9c00cd
Revises: cc92679c7c19
Create Date: 2026-05-30 07:16:38.759749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd8840e9c00cd'
down_revision: Union[str, Sequence[str], None] = 'cc92679c7c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_project_local_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash_bcrypt', sa.String(length=255), nullable=True),
    sa.Column('password_hash_md5', sa.String(length=255), nullable=True),
    sa.Column('password_hash_sha256', sa.String(length=255), nullable=True),
    sa.Column('password_hash_sha512', sa.String(length=255), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mw_project_local_user_email'), 'mw_project_local_user', ['email'], unique=True)
    op.create_index(op.f('ix_mw_project_local_user_project_id'), 'mw_project_local_user', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_project_local_user_username'), 'mw_project_local_user', ['username'], unique=True)
    op.add_column('mw_k8s_cluster_status', sa.Column('dex_installed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('dex_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'dex_version')
    op.drop_column('mw_k8s_cluster_status', 'dex_installed')
    op.drop_index(op.f('ix_mw_project_local_user_username'), table_name='mw_project_local_user')
    op.drop_index(op.f('ix_mw_project_local_user_project_id'), table_name='mw_project_local_user')
    op.drop_index(op.f('ix_mw_project_local_user_email'), table_name='mw_project_local_user')
    op.drop_table('mw_project_local_user')
    # ### end Alembic commands ###
