"""remove_unused_sources

Revision ID: da6577b1175f
Revises: ea885a937399
Create Date: 2026-06-11 13:32:18.457540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da6577b1175f'
down_revision: Union[str, Sequence[str], None] = 'ea885a937399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_streaming_source_project_id'), table_name='mw_streaming_source')
    op.drop_table('mw_streaming_source')
    op.drop_index(op.f('ix_mw_api_source_project_id'), table_name='mw_api_source')
    op.drop_table('mw_api_source')
    op.drop_index(op.f('ix_mw_web_source_project_id'), table_name='mw_web_source')
    op.drop_table('mw_web_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_web_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('enable_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verify_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('allowed_domains', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name=op.f('mw_web_source_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_web_source_pkey')),
    sa.UniqueConstraint('name', name=op.f('mw_web_source_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mw_web_source_project_id'), 'mw_web_source', ['project_id'], unique=False)
    op.create_table('mw_api_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('enable_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verify_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('api_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name=op.f('mw_api_source_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_api_source_pkey')),
    sa.UniqueConstraint('name', name=op.f('mw_api_source_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mw_api_source_project_id'), 'mw_api_source', ['project_id'], unique=False)
    op.create_table('mw_streaming_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('enable_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verify_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('broker_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bootstrap_servers', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extra_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], name=op.f('mw_streaming_source_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mw_streaming_source_pkey')),
    sa.UniqueConstraint('name', name=op.f('mw_streaming_source_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mw_streaming_source_project_id'), 'mw_streaming_source', ['project_id'], unique=False)
    # ### end Alembic commands ###
