# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add envoy_gateway_service_type to project

Revision ID: da790bf871f1
Revises: 3fd6ae8b321a
Create Date: 2026-06-26 16:51:53.887641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'da790bf871f1'
down_revision: Union[str, Sequence[str], None] = '3fd6ae8b321a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_project', sa.Column('envoy_gateway_service_type', sa.Enum('LoadBalancer', 'NodePort', name='envoygatewayservicetype', native_enum=False), server_default='LoadBalancer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_project', 'envoy_gateway_service_type')
    # ### end Alembic commands ###
