"""add override image and chart version to trino

Revision ID: dc3748cbcd22
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 14:06:44.593208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'dc3748cbcd22'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('chart_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='1.41.0'))
    op.add_column('mw_trino_platform', sa.Column('override_image', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_trino_platform', 'override_image')
    op.drop_column('mw_trino_platform', 'chart_version')
    # ### end Alembic commands ###
