"""remove unused modules

Revision ID: df775e492f08
Revises: a1fd5c41265e
Create Date: 2026-02-24 11:50:45.438481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df775e492f08"
down_revision: Union[str, Sequence[str], None] = "a1fd5c41265e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mw_ingestion_run_status"), table_name="mw_ingestion_run")
    op.drop_index(
        op.f("ix_mw_ingestion_run_ingestion_id"), table_name="mw_ingestion_run"
    )
    op.drop_table("mw_ingestion_run")

    op.drop_index(op.f("ix_mw_ingestion_s3_storage_id"), table_name="mw_ingestion")
    op.drop_index(op.f("ix_mw_ingestion_project_id"), table_name="mw_ingestion")
    op.drop_index(op.f("ix_mw_ingestion_data_source_id"), table_name="mw_ingestion")
    op.drop_table("mw_ingestion")

    op.drop_index(
        op.f("ix_mw_relationship_attribute_name"),
        table_name="mw_relationship_attribute",
    )
    op.drop_table("mw_relationship_attribute")

    op.drop_index(
        op.f("ix_mw_relationship_type_name"), table_name="mw_relationship_type"
    )
    op.drop_table("mw_relationship_type")

    op.drop_index(op.f("ix_mw_entity_attribute_name"), table_name="mw_entity_attribute")
    op.drop_table("mw_entity_attribute")

    op.drop_index(op.f("ix_mw_entity_type_name"), table_name="mw_entity_type")
    op.drop_table("mw_entity_type")

    op.drop_index(op.f("ix_mw_knowledge_db_type"), table_name="mw_knowledge_db")
    op.drop_index(op.f("ix_mw_knowledge_db_project_id"), table_name="mw_knowledge_db")
    op.drop_table("mw_knowledge_db")

    op.drop_index(op.f("ix_mw_chat_project_id"), table_name="mw_chat")
    op.drop_table("mw_chat")

    op.drop_index(op.f("ix_mw_ai_agent_project_id"), table_name="mw_ai_agent")
    op.drop_table("mw_ai_agent")

    op.drop_index(op.f("ix_mw_ontology_project_id"), table_name="mw_ontology")
    op.drop_table("mw_ontology")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mw_ontology",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('mw_ontology_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mw_project.id"], name="mw_ontology_project_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="mw_ontology_pkey"),
        sa.UniqueConstraint(
            "name",
            name="mw_ontology_name_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_mw_ontology_project_id"), "mw_ontology", ["project_id"], unique=False
    )

    op.create_table(
        "mw_entity_type",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('mw_entity_type_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ontology_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ontology_id"], ["mw_ontology.id"], name="mw_entity_type_ontology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="mw_entity_type_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_mw_entity_type_name"), "mw_entity_type", ["name"], unique=False
    )

    op.create_table(
        "mw_entity_attribute",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("data_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("required", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("entity_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_type_id"],
            ["mw_entity_type.id"],
            name=op.f("mw_entity_attribute_entity_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_entity_attribute_pkey")),
    )
    op.create_index(
        op.f("ix_mw_entity_attribute_name"),
        "mw_entity_attribute",
        ["name"],
        unique=False,
    )

    op.create_table(
        "mw_relationship_type",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('mw_relationship_type_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "source_entity_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "target_entity_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("ontology_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ontology_id"],
            ["mw_ontology.id"],
            name="mw_relationship_type_ontology_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="mw_relationship_type_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_mw_relationship_type_name"),
        "mw_relationship_type",
        ["name"],
        unique=False,
    )

    op.create_table(
        "mw_relationship_attribute",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("data_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("required", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "relationship_type_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["relationship_type_id"],
            ["mw_relationship_type.id"],
            name=op.f("mw_relationship_attribute_relationship_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_relationship_attribute_pkey")),
    )
    op.create_index(
        op.f("ix_mw_relationship_attribute_name"),
        "mw_relationship_attribute",
        ["name"],
        unique=False,
    )

    op.create_table(
        "mw_chat",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "messages",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("agent_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mw_project.id"], name=op.f("mw_chat_project_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_chat_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("mw_chat_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_mw_chat_project_id"), "mw_chat", ["project_id"], unique=False
    )

    op.create_table(
        "mw_ai_agent",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "temperature",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("system_prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "knowledge_db_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mw_project.id"], name=op.f("mw_ai_agent_project_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_ai_agent_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("mw_ai_agent_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_mw_ai_agent_project_id"), "mw_ai_agent", ["project_id"], unique=False
    )

    op.create_table(
        "mw_knowledge_db",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ontology_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ontology_id"],
            ["mw_ontology.id"],
            name=op.f("mw_knowledge_db_ontology_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mw_project.id"],
            name=op.f("mw_knowledge_db_project_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_knowledge_db_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("mw_knowledge_db_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_mw_knowledge_db_type"), "mw_knowledge_db", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_mw_knowledge_db_project_id"),
        "mw_knowledge_db",
        ["project_id"],
        unique=False,
    )

    op.create_table(
        "mw_ingestion",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("data_source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("s3_storage_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "storage_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "cron_schedule", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "ingestion_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["mw_datasource.id"],
            name=op.f("mw_ingestion_data_source_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mw_project.id"], name=op.f("mw_ingestion_project_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["s3_storage_id"],
            ["mw_s3_storage.id"],
            name=op.f("mw_ingestion_s3_storage_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_ingestion_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("mw_ingestion_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_mw_ingestion_data_source_id"),
        "mw_ingestion",
        ["data_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mw_ingestion_project_id"), "mw_ingestion", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_mw_ingestion_s3_storage_id"),
        "mw_ingestion",
        ["s3_storage_id"],
        unique=False,
    )

    op.create_table(
        "mw_ingestion_run",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ingestion_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "records_processed", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "error_message", sa.VARCHAR(length=1000), autoincrement=False, nullable=True
        ),
        sa.Column(
            "watermark_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["mw_ingestion.id"],
            name=op.f("mw_ingestion_run_ingestion_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mw_ingestion_run_pkey")),
    )
    op.create_index(
        op.f("ix_mw_ingestion_run_ingestion_id"),
        "mw_ingestion_run",
        ["ingestion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mw_ingestion_run_status"), "mw_ingestion_run", ["status"], unique=False
    )
    # ### end Alembic commands ###
