"""add ability to set ldap in trino

Revision ID: df81a3c06832
Revises: f8ff81b30ead
Create Date: 2026-03-15 09:31:15.351866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'df81a3c06832'
down_revision: Union[str, Sequence[str], None] = 'f8ff81b30ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('ldap_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_trino_platform', 'mw_ldap_config', ['ldap_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_trino_platform', type_='foreignkey')
    op.drop_column('mw_trino_platform', 'ldap_config_id')
    # ### end Alembic commands ###
