"""create ssh key and git repo tables

Revision ID: e48885dbe83c
Revises: 9353b022f9b1
Create Date: 2026-06-11 14:07:25.693050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e48885dbe83c'
down_revision: Union[str, Sequence[str], None] = '9353b022f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_ssh_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_ssh_key_project_id'), 'mw_ssh_key', ['project_id'], unique=False)
    op.create_table('mw_git_repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ssh_key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['mw_project.id'], ),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['mw_ssh_key.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mw_git_repo_project_id'), 'mw_git_repo', ['project_id'], unique=False)
    op.create_index(op.f('ix_mw_git_repo_ssh_key_id'), 'mw_git_repo', ['ssh_key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_git_repo_ssh_key_id'), table_name='mw_git_repo')
    op.drop_index(op.f('ix_mw_git_repo_project_id'), table_name='mw_git_repo')
    op.drop_table('mw_git_repo')
    op.drop_index(op.f('ix_mw_ssh_key_project_id'), table_name='mw_ssh_key')
    op.drop_table('mw_ssh_key')
    # ### end Alembic commands ###
