"""added defaultuser password field

Revision ID: ea885a937399
Revises: ba9fb2def85d
Create Date: 2026-06-10 13:08:59.835484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ea885a937399'
down_revision: Union[str, Sequence[str], None] = 'ba9fb2def85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_airflow_platform', sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE mw_airflow_platform SET admin_password = '' WHERE admin_password IS NULL")
    op.alter_column('mw_airflow_platform', 'admin_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_airflow_platform', 'admin_password')
    # ### end Alembic commands ###
