# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add doris operator to cluster status

Revision ID: f6ac271017e9
Revises: d048ea86e293
Create Date: 2026-08-18 16:54:07.814640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f6ac271017e9'
down_revision: Union[str, Sequence[str], None] = 'd048ea86e293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('doris_operator_installed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('doris_operator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'doris_operator_version')
    op.drop_column('mw_k8s_cluster_status', 'doris_operator_installed')
    # ### end Alembic commands ###
