# SPDX-FileCopyrightText: Copyright © 2026 Mohd Izhar Firdaus Bin Ismail
# SPDX-License-Identifier: AGPLv3+

"""add_envoy_gateway_and_ingress_domain

Revision ID: f799848ac67a
Revises: 53c979f5673b
Create Date: 2026-05-31 16:05:03.014750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f799848ac67a'
down_revision: Union[str, Sequence[str], None] = '53c979f5673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('envoy_gateway_installed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('envoy_gateway_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mw_project', sa.Column('ingress_domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_project', 'ingress_domain')
    op.drop_column('mw_k8s_cluster_status', 'envoy_gateway_version')
    op.drop_column('mw_k8s_cluster_status', 'envoy_gateway_installed')
    # ### end Alembic commands ###
