"""add nifikop operator status fields

Revision ID: f81c1d1a3974
Revises: 9c663be33267
Create Date: 2026-06-18 13:41:49.921532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f81c1d1a3974'
down_revision: Union[str, Sequence[str], None] = '9c663be33267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_k8s_cluster_status', sa.Column('nifikop_installed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mw_k8s_cluster_status', sa.Column('nifikop_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_k8s_cluster_status', 'nifikop_version')
    op.drop_column('mw_k8s_cluster_status', 'nifikop_installed')
    # ### end Alembic commands ###
