"""remove configurable iceberg port

Revision ID: f8ff81b30ead
Revises: fc14a7fecc90
Create Date: 2026-03-15 08:46:23.808032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f8ff81b30ead'
down_revision: Union[str, Sequence[str], None] = 'fc14a7fecc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_hive_metastore_platform', 'iceberg_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_hive_metastore_platform', sa.Column('iceberg_port', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
