"""add hive warehouse directory config

Revision ID: fc14a7fecc90
Revises: 10ad4a7ad73b
Create Date: 2026-03-14 21:16:22.151876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fc14a7fecc90'
down_revision: Union[str, Sequence[str], None] = '10ad4a7ad73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_hive_metastore_platform', sa.Column('warehouse_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='s3a://metastore/warehouse/'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_hive_metastore_platform', 'warehouse_dir')
    # ### end Alembic commands ###
