"""global_ldap_refactor_v2

Revision ID: ff7bd05f9c6c
Revises: d8959af48e47
Create Date: 2026-04-05 13:29:12.002865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ff7bd05f9c6c'
down_revision: Union[str, Sequence[str], None] = 'd8959af48e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mw_ldap_config_project_id'), table_name='mw_ldap_config')
    op.drop_constraint(op.f('mw_ldap_config_project_id_fkey'), 'mw_ldap_config', type_='foreignkey')
    op.drop_column('mw_ldap_config', 'project_id')
    op.add_column('mw_project', sa.Column('ldap_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mw_project', 'mw_ldap_config', ['ldap_config_id'], ['id'])
    op.drop_constraint(op.f('mw_superset_platform_ldap_config_id_fkey'), 'mw_superset_platform', type_='foreignkey')
    op.drop_column('mw_superset_platform', 'ldap_config_id')
    op.drop_constraint(op.f('mw_trino_platform_ldap_config_id_fkey'), 'mw_trino_platform', type_='foreignkey')
    op.drop_column('mw_trino_platform', 'ldap_config_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_trino_platform', sa.Column('ldap_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mw_trino_platform_ldap_config_id_fkey'), 'mw_trino_platform', 'mw_ldap_config', ['ldap_config_id'], ['id'])
    op.add_column('mw_superset_platform', sa.Column('ldap_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mw_superset_platform_ldap_config_id_fkey'), 'mw_superset_platform', 'mw_ldap_config', ['ldap_config_id'], ['id'])
    op.drop_constraint(None, 'mw_project', type_='foreignkey')
    op.drop_column('mw_project', 'ldap_config_id')
    op.add_column('mw_ldap_config', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mw_ldap_config_project_id_fkey'), 'mw_ldap_config', 'mw_project', ['project_id'], ['id'])
    op.create_index(op.f('ix_mw_ldap_config_project_id'), 'mw_ldap_config', ['project_id'], unique=False)
    # ### end Alembic commands ###
